/**
 * NOMENCLATURE - Consulting Cabinet (FOP 3rd Group)
 * 
 * Консультаційні послуги, навчання, аудит
 * Переважно послуги, мінімум товарних позицій
 */

import type { NomenclatureItemV2 } from "@/config/nomenclatureConfig";

export const consultingNomenclature: NomenclatureItemV2[] = [
  // === ПОСЛУГИ ===
  {
    id: "nom-cons-001",
    sku: "CONS-TAX-001",
    name: "Податкове консультування",
    shortName: "Подат. консульт.",
    category: "service",
    categoryId: "cat-consulting",
    tags: ["Популярне", "Ретейнер"],
    unitCode: "год",
    pricing: {
      basePrice: 1800,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 1800,
      priceTiers: [
        { minQuantity: 10, price: 1650, description: "Від 10 годин" },
        { minQuantity: 20, price: 1500, description: "Від 20 годин" },
      ],
      lastPriceChange: "2025-01-10",
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
      lastSyncAt: "2025-01-28T08:00:00Z",
    },
    isActive: true,
    isFavorite: true,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2025-01-28T08:00:00Z",
  },
  {
    id: "nom-cons-002",
    sku: "CONS-ACC-001",
    name: "Бухгалтерське обслуговування ФОП",
    shortName: "Бух. ФОП",
    category: "service",
    categoryId: "cat-accounting",
    tags: ["Ретейнер", "Місячний"],
    unitCode: "міс",
    pricing: {
      basePrice: 5000,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 5000,
      priceTiers: [
        { minQuantity: 6, price: 4500, description: "Контракт 6+ міс" },
        { minQuantity: 12, price: 4000, description: "Річний контракт" },
      ],
      lastPriceChange: "2024-11-01",
    },
    sync: {
      source: "1c",
      externalId: "1C-SRV-00123",
      syncStatus: "synced",
      lastSyncAt: "2025-01-28T06:00:00Z",
    },
    isActive: true,
    isFavorite: true,
    createdAt: "2023-06-01T10:00:00Z",
    updatedAt: "2025-01-28T06:00:00Z",
  },
  {
    id: "nom-cons-003",
    sku: "CONS-ACC-002",
    name: "Бухгалтерське обслуговування ТОВ",
    shortName: "Бух. ТОВ",
    category: "service",
    categoryId: "cat-accounting",
    tags: ["Ретейнер", "Enterprise"],
    unitCode: "міс",
    pricing: {
      basePrice: 15000,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 15000,
      priceTiers: [
        { minQuantity: 6, price: 13500, description: "Контракт 6+ міс" },
        { minQuantity: 12, price: 12000, description: "Річний контракт" },
      ],
    },
    sync: {
      source: "1c",
      externalId: "1C-SRV-00124",
      syncStatus: "conflict",
      lastSyncAt: "2025-01-27T18:00:00Z",
      conflictFields: ["pricing.basePrice"],
    },
    isActive: true,
    createdAt: "2023-06-01T10:00:00Z",
    updatedAt: "2025-01-27T18:00:00Z",
  },
  {
    id: "nom-cons-004",
    sku: "CONS-AUD-001",
    name: "Аудит фінансової звітності",
    shortName: "Аудит ФЗ",
    description: "Повний аудит річної фінансової звітності з висновком",
    category: "service",
    categoryId: "cat-audit",
    tags: ["Проектний", "Сезонний"],
    unitCode: "проект",
    pricing: {
      basePrice: 35000,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 35000,
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
    },
    isActive: true,
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-12-15T14:00:00Z",
  },
  {
    id: "nom-cons-005",
    sku: "CONS-EDU-001",
    name: "Корпоративний тренінг з оподаткування",
    shortName: "Тренінг подат.",
    description: "8-годинний тренінг для бухгалтерів компанії",
    category: "service",
    categoryId: "cat-education",
    tags: ["Навчання", "Груповий"],
    unitCode: "сесія",
    pricing: {
      basePrice: 12000,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 12000,
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
    },
    isActive: true,
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2024-09-10T10:00:00Z",
  },
  {
    id: "nom-cons-006",
    sku: "CONS-REP-001",
    name: "Підготовка податкової звітності ФОП",
    shortName: "Звітність ФОП",
    category: "service",
    categoryId: "cat-reporting",
    tags: ["Сезонний"],
    unitCode: "квартал",
    pricing: {
      basePrice: 2500,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 2500,
    },
    sync: {
      source: "medoc",
      externalId: "MDOC-SRV-456",
      syncStatus: "synced",
      lastSyncAt: "2025-01-25T12:00:00Z",
    },
    isActive: true,
    isFavorite: true,
    createdAt: "2023-01-01T10:00:00Z",
    updatedAt: "2025-01-25T12:00:00Z",
  },
  {
    id: "nom-cons-007",
    sku: "CONS-REP-002",
    name: "Підготовка статистичної звітності",
    shortName: "Статзвітність",
    category: "service",
    categoryId: "cat-reporting",
    unitCode: "звіт",
    pricing: {
      basePrice: 800,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 800,
    },
    sync: {
      source: "medoc",
      externalId: "MDOC-SRV-457",
      syncStatus: "pending",
      lastSyncAt: "2025-01-20T10:00:00Z",
    },
    isActive: true,
    createdAt: "2023-01-01T10:00:00Z",
    updatedAt: "2025-01-20T10:00:00Z",
  },
  {
    id: "nom-cons-008",
    sku: "CONS-DUE-001",
    name: "Due Diligence (фінансовий аналіз)",
    shortName: "Due Diligence",
    description: "Комплексна перевірка фінансового стану компанії",
    category: "service",
    categoryId: "cat-audit",
    tags: ["Проектний", "M&A"],
    unitCode: "проект",
    pricing: {
      basePrice: 75000,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 75000,
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
    },
    isActive: true,
    createdAt: "2024-06-01T10:00:00Z",
    updatedAt: "2024-06-01T10:00:00Z",
  },
  
  // === ТОВАРИ (документи, підписки) ===
  {
    id: "nom-cons-009",
    sku: "PROD-BOOK-001",
    barcode: "4820001234567",
    name: "Посібник \"Оподаткування ФОП 2025\"",
    shortName: "Посібник ФОП",
    category: "product",
    categoryId: "cat-publications",
    tags: ["Друк"],
    unitCode: "шт",
    pricing: {
      basePrice: 450,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 450,
    },
    stock: {
      quantity: 25,
      reserved: 3,
      available: 22,
      reorderPoint: 10,
      status: "in-stock",
      lastUpdated: "2025-01-28T09:00:00Z",
    },
    logistics: {
      weight: 0.35,
      dimensions: { length: 21, width: 15, height: 2 },
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
    },
    isActive: true,
    createdAt: "2024-12-01T10:00:00Z",
    updatedAt: "2025-01-28T09:00:00Z",
  },
  {
    id: "nom-cons-010",
    sku: "PROD-SUB-001",
    name: "Річна підписка на консультації",
    shortName: "Підписка рік",
    description: "Необмежена кількість email/чат консультацій протягом року",
    category: "product",
    categoryId: "cat-subscriptions",
    tags: ["Підписка", "VIP"],
    unitCode: "шт",
    pricing: {
      basePrice: 24000,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 24000,
    },
    stock: {
      quantity: 100,
      reserved: 0,
      available: 100,
      reorderPoint: 0,
      status: "in-stock",
      lastUpdated: "2025-01-28T09:00:00Z",
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
    },
    isActive: true,
    createdAt: "2024-01-01T10:00:00Z",
    updatedAt: "2025-01-01T10:00:00Z",
  },
];
