/**
 * NOMENCLATURE - IT Cabinet (FOP 3rd Group)
 * 
 * IT-послуги та розробка ПЗ
 * Переважно послуги, валютні контракти
 */

import type { NomenclatureItemV2 } from "@/config/nomenclatureConfig";

export const itNomenclature: NomenclatureItemV2[] = [
  // === ПОСЛУГИ ===
  {
    id: "nom-it-001",
    sku: "DEV-HOUR-001",
    name: "Розробка ПЗ (година)",
    shortName: "Dev Hour",
    description: "Software development services",
    category: "service",
    categoryId: "cat-development",
    tags: ["Популярне", "USD"],
    unitCode: "год",
    pricing: {
      basePrice: 50,
      currency: "USD",
      vatRate: 0,
      priceWithVat: 50,
      priceTiers: [
        { minQuantity: 160, price: 45, description: "Full-time monthly" },
      ],
      lastPriceChange: "2025-01-01",
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
    },
    isActive: true,
    isFavorite: true,
    createdAt: "2022-01-01T10:00:00Z",
    updatedAt: "2025-01-01T10:00:00Z",
  },
  {
    id: "nom-it-002",
    sku: "DEV-SENIOR-001",
    name: "Senior Developer (місяць)",
    shortName: "Senior Dev/mo",
    description: "Senior developer monthly engagement",
    category: "service",
    categoryId: "cat-development",
    tags: ["Контракт", "EUR"],
    unitCode: "міс",
    pricing: {
      basePrice: 6500,
      currency: "EUR",
      vatRate: 0,
      priceWithVat: 6500,
    },
    sync: {
      source: "api",
      externalId: "UPWORK-CONTRACT-123",
      syncStatus: "synced",
      lastSyncAt: "2025-01-28T10:00:00Z",
    },
    isActive: true,
    isFavorite: true,
    createdAt: "2023-06-01T10:00:00Z",
    updatedAt: "2025-01-28T10:00:00Z",
  },
  {
    id: "nom-it-003",
    sku: "DEV-WEB-001",
    name: "Розробка веб-сайту (лендінг)",
    shortName: "Лендінг",
    description: "Single page website with modern design",
    category: "service",
    categoryId: "cat-web",
    tags: ["Проект", "UAH"],
    unitCode: "проект",
    pricing: {
      basePrice: 25000,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 25000,
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
    },
    isActive: true,
    createdAt: "2023-01-01T10:00:00Z",
    updatedAt: "2024-08-15T10:00:00Z",
  },
  {
    id: "nom-it-004",
    sku: "DEV-WEB-002",
    name: "Розробка корпоративного сайту",
    shortName: "Корп. сайт",
    description: "Multi-page corporate website with CMS",
    category: "service",
    categoryId: "cat-web",
    tags: ["Проект", "UAH"],
    unitCode: "проект",
    pricing: {
      basePrice: 80000,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 80000,
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
    },
    isActive: true,
    createdAt: "2023-02-01T10:00:00Z",
    updatedAt: "2024-09-20T10:00:00Z",
  },
  {
    id: "nom-it-005",
    sku: "DEV-MOB-001",
    name: "Розробка мобільного додатку",
    shortName: "Mobile App",
    description: "Cross-platform mobile application (iOS + Android)",
    category: "service",
    categoryId: "cat-mobile",
    tags: ["Проект", "USD"],
    unitCode: "проект",
    pricing: {
      basePrice: 15000,
      currency: "USD",
      vatRate: 0,
      priceWithVat: 15000,
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
    },
    isActive: true,
    createdAt: "2023-03-01T10:00:00Z",
    updatedAt: "2024-07-10T10:00:00Z",
  },
  {
    id: "nom-it-006",
    sku: "DEV-API-001",
    name: "Інтеграція API",
    shortName: "API Integration",
    description: "Third-party API integration service",
    category: "service",
    categoryId: "cat-integration",
    tags: ["UAH"],
    unitCode: "шт",
    pricing: {
      basePrice: 12000,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 12000,
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
    },
    isActive: true,
    createdAt: "2023-04-01T10:00:00Z",
    updatedAt: "2024-06-15T10:00:00Z",
  },
  {
    id: "nom-it-007",
    sku: "CONS-IT-001",
    name: "IT-консультація",
    shortName: "IT Consult",
    description: "Technical consultation and architecture review",
    category: "service",
    categoryId: "cat-consulting",
    tags: ["Популярне"],
    unitCode: "год",
    pricing: {
      basePrice: 2000,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 2000,
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
    },
    isActive: true,
    isFavorite: true,
    createdAt: "2022-06-01T10:00:00Z",
    updatedAt: "2024-12-01T10:00:00Z",
  },
  {
    id: "nom-it-008",
    sku: "SUP-WEB-001",
    name: "Технічна підтримка сайту",
    shortName: "Support Web",
    description: "Monthly website maintenance and support",
    category: "service",
    categoryId: "cat-support",
    tags: ["Ретейнер"],
    unitCode: "міс",
    pricing: {
      basePrice: 5000,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 5000,
      priceTiers: [
        { minQuantity: 6, price: 4500, description: "6+ місяців" },
        { minQuantity: 12, price: 4000, description: "Річний контракт" },
      ],
    },
    sync: {
      source: "vchasno",
      externalId: "VCH-SRV-789",
      syncStatus: "synced",
      lastSyncAt: "2025-01-27T16:00:00Z",
    },
    isActive: true,
    createdAt: "2023-01-01T10:00:00Z",
    updatedAt: "2025-01-27T16:00:00Z",
  },
  {
    id: "nom-it-009",
    sku: "DEV-CODE-001",
    name: "Code Review",
    shortName: "Code Review",
    description: "Professional code review and recommendations",
    category: "service",
    categoryId: "cat-development",
    unitCode: "год",
    pricing: {
      basePrice: 75,
      currency: "USD",
      vatRate: 0,
      priceWithVat: 75,
    },
    sync: {
      source: "api",
      syncStatus: "pending",
      lastSyncAt: "2025-01-20T10:00:00Z",
    },
    isActive: true,
    createdAt: "2024-01-01T10:00:00Z",
    updatedAt: "2025-01-20T10:00:00Z",
  },
  {
    id: "nom-it-010",
    sku: "DEV-DEVOPS-001",
    name: "DevOps консалтинг",
    shortName: "DevOps",
    description: "CI/CD setup, cloud infrastructure consulting",
    category: "service",
    categoryId: "cat-devops",
    tags: ["USD"],
    unitCode: "год",
    pricing: {
      basePrice: 80,
      currency: "USD",
      vatRate: 0,
      priceWithVat: 80,
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
    },
    isActive: true,
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2024-12-15T10:00:00Z",
  },
  
  // === ТОВАРИ (ліцензії) ===
  {
    id: "nom-it-011",
    sku: "LIC-SaaS-001",
    uktzedCode: "8523492900",
    name: "Ліцензія SaaS продукту (річна)",
    shortName: "SaaS License",
    description: "Annual SaaS product license",
    category: "product",
    categoryId: "cat-licenses",
    tags: ["Підписка"],
    unitCode: "шт",
    pricing: {
      basePrice: 12000,
      currency: "UAH",
      vatRate: 0,
      priceWithVat: 12000,
    },
    stock: {
      quantity: 999,
      reserved: 0,
      available: 999,
      reorderPoint: 0,
      status: "in-stock",
      lastUpdated: "2025-01-28T10:00:00Z",
    },
    sync: {
      source: "manual",
      syncStatus: "synced",
    },
    isActive: true,
    createdAt: "2024-01-01T10:00:00Z",
    updatedAt: "2025-01-01T10:00:00Z",
  },
];
