import type { Cabinet } from "@/types/cabinet";

// Helper to get dates relative to today
const getDateFromNow = (days: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().split("T")[0];
};

export const mockCabinets: Cabinet[] = [
  {
    id: "1",
    name: "ТОВ «Ромашка»",
    taxId: "12345678",
    type: "tov",
    typeLabel: "Загальна система",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 250000,
    reportStatus: "ok",
    nextDeadline: getDateFromNow(3),
    deadlineLabel: "Подача декларації ПДВ",
  },
  {
    id: "2",
    name: "ФОП Іваненко Іван Іванович",
    taxId: "1234567890",
    type: "fop",
    typeLabel: "3 група без ПДВ",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 420000,
    reportStatus: "tasks",
    nextDeadline: getDateFromNow(5),
    deadlineLabel: "Сплата ЄСВ",
    fopGroup: 3,
    yearlyIncome: 8450000, // 90% ліміту — критична зона
    hasEmployees: true,
  },
  {
    id: "3",
    name: "ТОВ «Технолоджі Плюс»",
    taxId: "87654321",
    type: "tov",
    typeLabel: "Загальна система",
    role: "accountant",
    roleLabel: "Бухгалтер",
    status: "active",
    monthlyIncome: 1200000,
    reportStatus: "ok",
    nextDeadline: getDateFromNow(2),
    deadlineLabel: "Подача звітності",
  },
  {
    id: "4",
    name: "ФОП Петренко О.В.",
    taxId: "2345678901",
    type: "fop",
    typeLabel: "2 група",
    role: "accountant",
    roleLabel: "Бухгалтер",
    status: "active",
    monthlyIncome: 380000,
    reportStatus: "ok",
    nextDeadline: getDateFromNow(10),
    deadlineLabel: "Квартальний звіт",
    fopGroup: 2,
    yearlyIncome: 5100000, // 91% ліміту — критична зона
    hasEmployees: false,
  },
  {
    id: "9",
    name: "ФОП Козаченко В.М.",
    taxId: "5678901234",
    type: "fop",
    typeLabel: "1 група",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 75000,
    reportStatus: "tasks",
    nextDeadline: getDateFromNow(2),
    deadlineLabel: "Ліміт доходу!",
    fopGroup: 1,
    yearlyIncome: 1050000, // 94% ліміту — критична зона
    hasEmployees: false,
  },
  {
    // Кабінет компанії-власника системи (dogfooding).
    // Раніше тут був "Група ФОП «Консалтинг»" (fop-group) — юридично неіснуючий тип.
    id: "5",
    name: "ТОВ «Fintodo»",
    taxId: "44556677",
    type: "tov",
    typeLabel: "Загальна система • IT / SaaS",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 2_400_000,
    yearlyIncome: 24_800_000,
    hasEmployees: true,
    industry: "it",
    // Fintodo — SaaS-кабінет: працівники + ПДВ + основні засоби + власні
    // SaaS-операції. Складу немає → tab «Склад» автоматично прихований.
    capabilities: ["employees", "vat", "fixed_assets", "saas_business"],
    reportStatus: "tasks",
    nextDeadline: getDateFromNow(6),
    deadlineLabel: "Декларація з податку на прибуток",
  },
  {
    id: "6",
    name: "ТОВ «Старий Проєкт»",
    taxId: "11223344",
    type: "tov",
    typeLabel: "Спрощена система",
    role: "owner",
    roleLabel: "Власник",
    status: "archived",
    monthlyIncome: 0,
    reportStatus: "ok",
  },
  {
    id: "7",
    name: "Коваленко Марія Олексіївна",
    taxId: "3456789012",
    type: "individual",
    typeLabel: "Декларант ПДФО",
    role: "accountant",
    roleLabel: "Бухгалтер",
    status: "active",
    monthlyIncome: 28000,
    reportStatus: "ok",
    nextDeadline: getDateFromNow(15),
    deadlineLabel: "Декларація про доходи",
  },
  {
    id: "8",
    name: "Сидоренко Іван Петрович",
    taxId: "4567890123",
    type: "individual",
    typeLabel: "Орендодавець",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 15000,
    reportStatus: "tasks",
    nextDeadline: getDateFromNow(4),
    deadlineLabel: "Сплата податку на нерухомість",
  },
  // Test passive cabinet for demo (contractor onboarding result)
  {
    id: "passive-demo-1",
    name: 'ТОВ "Технопром Груп"',
    taxId: "32855961", // Валідний ЄДРПОУ
    type: "tov",
    typeLabel: "Пасивний кабінет",
    role: "owner",
    roleLabel: "Контрагент",
    status: "active",
    monthlyIncome: 0,
    reportStatus: "ok",
    accessMode: "passive",
    invitedByCabinetId: "2", // ФОП Іваненко І.І.
    invitedAt: "2024-12-15T10:30:00.000Z", // Фіксована дата для демо
  },
  
  // ============================================
  // ДЕМО-КАБІНЕТИ ДЛЯ БІЗНЕС-СЦЕНАРІЇВ
  // ============================================
  
  // 1. ФОП Консалтинг — 3 група, 3 працівники, гранти, фінмоніторинг
  {
    id: "demo-consulting-3",
    name: "ФОП Шевченко Михайло Олександрович",
    taxId: "3112345678",
    type: "fop",
    typeLabel: "3 група без ПДВ",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 625000,
    reportStatus: "tasks",
    nextDeadline: getDateFromNow(8),
    deadlineLabel: "Квартальний звіт",
    fopGroup: 3,
    yearlyIncome: 7500000, // 80% ліміту
    hasEmployees: true,
    industry: "consulting",
  },
  
  // 2. ФОП Авторемонт — 2 група, 2 працівники, касові операції, РРО
  {
    id: "demo-autorepair-2",
    name: "ФОП Бойко Віталій Ігорович",
    taxId: "2987654321",
    type: "fop",
    typeLabel: "2 група",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 400000,
    reportStatus: "tasks",
    nextDeadline: getDateFromNow(5),
    deadlineLabel: "Оренда СТО",
    fopGroup: 2,
    yearlyIncome: 4800000, // 86% ліміту 2 групи
    hasEmployees: true,
    industry: "autorepair",
  },
  
  // 3. ФОП IT — 3 група, solo, іноземні контракти, валюта
  {
    id: "demo-it-3",
    name: "ФОП Коваль Андрій Сергійович",
    taxId: "3245678901",
    type: "fop",
    typeLabel: "3 група без ПДВ",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 266700,
    reportStatus: "ok",
    nextDeadline: getDateFromNow(12),
    deadlineLabel: "Подача декларації",
    fopGroup: 3,
    yearlyIncome: 3200000, // 34% ліміту
    hasEmployees: false,
    industry: "it",
  },
  
  // 4. ФОП Дилер/Торгівля — 2 група, 1 працівник, товарний облік, критична зона ліміту
  {
    id: "demo-dealer-2",
    name: "ФОП Кравченко Олег Петрович",
    taxId: "2876543210",
    type: "fop",
    typeLabel: "2 група",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 458000,
    reportStatus: "tasks",
    nextDeadline: getDateFromNow(2),
    deadlineLabel: "Ліміт критичний!",
    fopGroup: 2,
    yearlyIncome: 5500000, // 98% ліміту 2 групи — критична зона!
    hasEmployees: true,
    industry: "dealer",
  },
  // 5. Фізична особа-декларант — інвестиції, іноземний дохід, продаж авто, податкова знижка
  {
    id: "demo-individual-declarant",
    name: "Ткаченко Ольга Вікторівна",
    taxId: "2856734190",
    type: "individual",
    typeLabel: "Декларант ПДФО",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 74300,
    reportStatus: "tasks",
    nextDeadline: getDateFromNow(52),
    deadlineLabel: "Декларація до 01.05",
    industry: "investing",
  },
  // 6. ФОП Салон краси «Beauty Lab» — 3 група 5%, 3 штатні + 7 ФОП-майстри, бронювання, ПРРО
  {
    id: "demo-salon-3",
    name: "ФОП Романюк Ірина Володимирівна",
    taxId: "3198765432",
    type: "fop",
    typeLabel: "3 група без ПДВ",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 285000,
    reportStatus: "ok",
    nextDeadline: getDateFromNow(15),
    deadlineLabel: "Декларація ЄП Q1",
    fopGroup: 3,
    yearlyIncome: 3245000, // 43% ліміту 3 групи
    hasEmployees: true,
    industry: "salon",
  },
  // 6b. ФОП Тенісний клуб «Ace Court» — 3 група 5%, 8 кортів, магазин 50 SKU + кафе 30 SKU (2 ПРРО),
  //     3 штатні + 2 ФОП-тренери, бронювання кортів/тренувань/прокату.
  {
    id: "demo-tennis-3",
    name: "ФОП Коваленко Павло Андрійович",
    taxId: "3287654321",
    type: "fop",
    typeLabel: "3 група без ПДВ",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 412000,
    reportStatus: "ok",
    nextDeadline: getDateFromNow(18),
    deadlineLabel: "Декларація ЄП Q1",
    fopGroup: 3,
    yearlyIncome: 4865000, // ≈52% ліміту 3 групи 2026
    hasEmployees: true,
    industry: "tennis_club",
  },
  // 6c. ФОП Ресторан «Смак» — 3 група 5%, 25 столиків, 150 SKU,
  //     3 кухарі (2 штат + 1 ФОП), 4 офіціанти (2 штат + 2 ФОП),
  //     2 адміни (штат), 2 ПРРО (Зал + Кухня/Доставка), власна доставка.
  {
    id: "demo-restaurant-3",
    name: "ФОП Шевченко Олег Іванович",
    taxId: "3312345678",
    type: "fop",
    typeLabel: "3 група без ПДВ",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 582000,
    reportStatus: "ok",
    nextDeadline: getDateFromNow(20),
    deadlineLabel: "Декларація ЄП Q1",
    fopGroup: 3,
    yearlyIncome: 6870000, // ≈73% ліміту 3 групи 2026
    hasEmployees: true,
    industry: "restaurant",
  },
  // 6d. ФОП Готель «Затишок» — 3 група 5%, 30 номерів (Standard/Superior/Suite),
  //     150 SKU (mini-bar / сніданок / SPA / готельні товари), 1 ПРРО Reception,
  //     9 штатних (4 housekeeping + 2 техмайстри + 2 ресепшн + 1 керівник)
  //     + 1 ФОП-прибиральниця (договір ЦПХ).
  {
    id: "demo-hotel-3",
    name: "ФОП Бондаренко Наталія Володимирівна",
    taxId: "3398765012",
    type: "fop",
    typeLabel: "3 група без ПДВ",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    monthlyIncome: 685000,
    reportStatus: "ok",
    nextDeadline: getDateFromNow(22),
    deadlineLabel: "Декларація ЄП Q1",
    fopGroup: 3,
    yearlyIncome: 7920000, // ≈85% ліміту 3 групи 2026
    hasEmployees: true,
    industry: "hotel",
  },
  // 7. Особисті кабінети штатних майстрів салону (трудові договори).
  //    `bookings_personal` НЕ задаємо явно — capability виводиться через
  //    `deriveCapabilities()` за наявністю активної делегації salon-master.
  {
    id: "ind-master-s-1",
    name: "Гриценко Світлана Петрівна",
    taxId: "2891234567",
    type: "individual",
    typeLabel: "Фізична особа · майстер",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    industry: "salon",
  },
  {
    id: "ind-master-s-2",
    name: "Бондар Олена Михайлівна",
    taxId: "2945671230",
    type: "individual",
    typeLabel: "Фізична особа · майстриня",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    industry: "salon",
  },
  {
    id: "ind-master-s-3",
    name: "Лисенко Андрій Олегович",
    taxId: "2812349876",
    type: "individual",
    typeLabel: "Фізична особа · майстер",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    industry: "salon",
  },
  // 8. Особистий кабінет ФОП-майстра (revenue_split — без ФОП-кабінету не критично,
  //    але потрібен для актів виконаних робіт салону).
  {
    id: "ind-master-f-1",
    name: "Сидоренко Анна Володимирівна",
    taxId: "3001234567",
    type: "individual",
    typeLabel: "Фізична особа · ФОП-майстер",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    industry: "salon",
  },
  {
    id: "fop-master-f-1",
    name: "ФОП Сидоренко Анна Володимирівна",
    taxId: "3001234567",
    type: "fop",
    typeLabel: "3 група 5%",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    fopGroup: 3,
    yearlyIncome: 412000,
    hasEmployees: false,
    industry: "salon",
  },
  // 9. Особистий кабінет ФОП-майстра, що орендує робоче місце.
  {
    id: "ind-master-f-7",
    name: "Назаренко Дмитро Васильович",
    taxId: "3056781234",
    type: "individual",
    typeLabel: "Фізична особа · ФОП-майстер",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    industry: "salon",
  },
  {
    id: "fop-master-f-7",
    name: "ФОП Назаренко Дмитро Васильович",
    taxId: "3056781234",
    type: "fop",
    typeLabel: "2 група",
    role: "owner",
    roleLabel: "Власник",
    status: "active",
    fopGroup: 2,
    yearlyIncome: 538000,
    hasEmployees: false,
    industry: "salon",
  },
];


export const typeOptions = [
  { value: "all", label: "Усі типи" },
  { value: "fop", label: "ФОП" },
  { value: "tov", label: "ТОВ" },
  { value: "individual", label: "Фізична особа" },
];

export const roleOptions = [
  { value: "all", label: "Усі ролі" },
  { value: "owner", label: "Власник" },
  { value: "accountant", label: "Бухгалтер" },
  { value: "auditor", label: "Аудитор" },
];

export const statusOptions = [
  { value: "all", label: "Усі статуси" },
  { value: "active", label: "Активний" },
  { value: "archived", label: "Архівний" },
];
