/**
 * AUTOREPAIR CABINET (demo-autorepair-2)
 * ФОП Бойко В.І. — Авторемонт, 2 група, 2 працівники
 */

import type { Document } from "@/config/documentFlowConfig";
import type { IncomeBookRecord } from "@/config/incomeBookConfig";
import type { TaxPayment, ContractorPayment, SalaryPayment } from "@/config/paymentsConfig";
import type { Contractor } from "@/config/settingsConfig";
import type { Employee } from "@/config/employeesConfig";
import type { Report, ReportStatus } from "@/config/reportsConfig";
import { getDateFromNow, getDateInPast } from "./helpers";

// Cabinet identity for all Autorepair documents
const AUTOREPAIR_CABINET = {
  cabinetId: "demo-autorepair-2",
  cabinetName: "ФОП Бойко В.І.",
  cabinetCode: "2223334455",
};

// ============================================
// DOCUMENTS
// ============================================

export const autorepairDocuments: Document[] = [
  // Договір оренди СТО
  {
    id: "doc-auto-001",
    ...AUTOREPAIR_CABINET,
    number: "ОРЕНДА-СТО-2025",
    type: "rental-agreement",
    category: "contract",
    title: "Договір оренди приміщення СТО",
    date: "2025-01-01",
    dueDate: "2025-12-31",
    amount: 35000,
    currency: "UAH",
    contractor: { id: "c-auto-1", name: "ТОВ «АвтоПарк»", code: "22334455" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-01-01T08:00:00Z",
    createdBy: "contractor",
    updatedAt: "2025-01-01T12:00:00Z",
    aiSummary: "Договір оренди приміщення СТО площею 300 м² за 35 000 ₴/міс. Орендодавець — ТОВ «АвтоПарк». Оплата до 5 числа кожного місяця.",
    // Template-based fieldValues for unified display
    templateId: "sys-contract-rental",
    fieldValues: {
      documentNumber: "ОРЕНДА-СТО-2025",
      documentDate: "2025-01-01",
      landlordName: "ТОВ «АвтоПарк»",
      landlordCode: "22334455",
      tenantName: "ФОП Бойко В.І.",
      tenantCode: "2223334455",
      rentalObject: "Приміщення СТО, 300 м²",
      monthlyRent: "35000",
      validTo: "2025-12-31",
    },
    aiRisks: [
      {
        id: "r-auto-001-1",
        category: "financial",
        title: "Відсутня індексація орендної плати",
        description: "Договір не передбачає індексацію плати на рівень інфляції, що може призвести до невигідних умов для орендодавця.",
        severity: "low",
        sourceSection: "п. 4.1 «Орендна плата»",
        suggestion: {
          text: "Рекомендую додати пункт про щорічну індексацію орендної плати на рівень офіційної інфляції для уникнення конфліктів при перегляді умов.",
          targetSection: "Орендна плата",
          insertPosition: "append",
          confidence: 76,
        },
      },
    ],
  },
  // Договір зі страховою
  {
    id: "doc-auto-002",
    ...AUTOREPAIR_CABINET,
    number: "СТРАХ-2025-001",
    type: "contract",
    category: "contract",
    title: "Договір про співпрацю зі СК «АвтоГарант»",
    date: "2025-01-15",
    dueDate: "2026-01-15",
    amount: 0,
    currency: "UAH",
    contractor: { id: "c-auto-2", name: "СК «АвтоГарант»", code: "44556677" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-01-15T10:00:00Z",
    createdBy: "contractor",
    updatedAt: "2025-01-15T14:00:00Z",
    aiSummary: "Договір про виконання ремонтних робіт за страховими замовленнями зі СК «АвтоГарант». Комісія 15% від кожного замовлення.",
    // Template-based fieldValues for unified display
    templateId: "sys-contract-services",
    fieldValues: {
      documentNumber: "СТРАХ-2025-001",
      documentDate: "2025-01-15",
      executorName: "ФОП Бойко В.І.",
      executorCode: "2223334455",
      customerName: "СК «АвтоГарант»",
      customerCode: "44556677",
      subject: "Виконання ремонтних робіт за страховими замовленнями. Комісія 15%.",
      validFrom: "2025-01-15",
      validTo: "2026-01-15",
    },
    aiRisks: [
      {
        id: "r-auto-002-1",
        category: "financial",
        title: "Комісія 15% не зафіксована явно",
        description: "Розмір комісії згадується в додатку, але не в основному тексті договору.",
        severity: "medium",
        sourceSection: "Додаток №1",
        suggestion: {
          text: "Рекомендую внести розмір комісії (15%) безпосередньо до основного тексту договору для уникнення непорозумінь при розрахунках.",
          targetSection: "п. 5.1 «Винагорода»",
          insertPosition: "replace",
          confidence: 85,
        },
      },
    ],
  },
  // Накладна на запчастини (вхідна)
  {
    id: "doc-auto-003",
    ...AUTOREPAIR_CABINET,
    number: "НКЛ-IN-2025-001",
    type: "invoice",
    category: "primary",
    title: "Накладна на запчастини від ТОВ «АвтоДеталь»",
    date: getDateInPast(7),
    amount: 45000,
    currency: "UAH",
    contractor: { id: "c-auto-3", name: "ТОВ «АвтоДеталь»", code: "55667788" },
    status: "confirmed",
    retentionPeriod: 3,
    createdAt: getDateInPast(7) + "T11:00:00Z",
    createdBy: "contractor",
    updatedAt: getDateInPast(6) + "T09:00:00Z",
    aiSummary: "Вхідна накладна на закупівлю запчастин від ТОВ «АвтоДеталь» на суму 45 000 ₴. Товар прийнято на склад.",
  },
  // Акт виконаних робіт (страхове замовлення)
  {
    id: "doc-auto-004",
    ...AUTOREPAIR_CABINET,
    number: "АКТ-СТРАХ-2025-001",
    type: "act",
    category: "primary",
    title: "Акт виконаних робіт — страхове замовлення №1234",
    date: getDateInPast(10),
    amount: 28500,
    currency: "UAH",
    contractor: { id: "c-auto-2", name: "СК «АвтоГарант»", code: "44556677" },
    status: "signed",
    retentionPeriod: 3,
    createdAt: getDateInPast(10) + "T15:00:00Z",
    createdBy: "owner",
    updatedAt: getDateInPast(9) + "T10:00:00Z",
    aiSummary: "Акт виконаних ремонтних робіт за страховим замовленням №1234 на суму 28 500 ₴. Замовник — СК «АвтоГарант». Підписано обома сторонами.",
    // Template-based fieldValues for unified display
    templateId: "sys-act-standard",
    fieldValues: {
      documentNumber: "АКТ-СТРАХ-2025-001",
      documentDate: getDateInPast(10),
      total: "28500",
      executorName: "ФОП Бойко В.І.",
      executorCode: "2223334455",
      customerName: "СК «АвтоГарант»",
      customerCode: "44556677",
      subject: "Ремонтні роботи за страховим замовленням №1234",
    },
  },
  // Комісійний договір
  {
    id: "doc-auto-005",
    number: "КОМІС-2025-001",
    type: "contract",
    category: "contract",
    title: "Договір комісії на продаж запчастин",
    date: "2025-02-01",
    dueDate: "2025-12-31",
    currency: "UAH",
    contractor: { id: "c-auto-4", name: "ФОП Шевченко П.О.", code: "6677889900" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-02-01T09:00:00Z",
    createdBy: "contractor",
    updatedAt: "2025-02-01T12:00:00Z",
    aiSummary: "Договір комісії КОМІС-2025-001 від 01.02.2025 з ФОП Шевченко П.О. Продаж запчастин на комісійних умовах. Дійсний до 31.12.2025.",
    aiRisks: [
      {
        id: "r-auto-005-1",
        category: "financial",
        title: "Умови комісії не деталізовані",
        description: "Відсоток комісійної винагороди та порядок розрахунків потребують уточнення.",
        severity: "low",
        sourceSection: "п. 4.1 «Винагорода»",
        suggestion: {
          text: "Рекомендую додати до договору чітко визначений відсоток комісії та терміни перерахування коштів за продані товари.",
          targetSection: "Винагорода",
          insertPosition: "append",
          confidence: 78,
        },
      },
    ],
  },
  // Заявка-наряд
  {
    id: "doc-auto-006",
    number: "ЗН-2025-045",
    type: "act",
    category: "primary",
    title: "Заявка-наряд на ремонт №045",
    date: getDateInPast(2),
    amount: 15800,
    currency: "UAH",
    contractor: { id: "c-auto-5", name: "Фізична особа", code: "" },
    status: "pending-sign",
    retentionPeriod: 3,
    createdAt: getDateInPast(2) + "T14:00:00Z",
    createdBy: "owner",
    updatedAt: getDateInPast(2) + "T14:00:00Z",
    aiSummary: "Заявка-наряд ЗН-2025-045 від " + getDateInPast(2) + " на ремонт автомобіля для фізичної особи. Кузовний ремонт на 15 800 ₴. Очікує підпису клієнта.",
    aiRisks: [
      {
        id: "r1",
        category: "counterparty",
        title: "Відсутні документи на авто",
        description: "Клієнт не надав документи на авто для оформлення замовлення",
        severity: "medium",
        sourceSection: "AI analysis",
        suggestion: {
          text: "Додати до п. 2.1: «Замовник зобов'язаний надати копії свідоцтва про реєстрацію транспортного засобу та технічного паспорта до початку виконання робіт»",
          targetSection: "п. 2.1",
          insertPosition: "append",
          confidence: 87,
        },
      },
    ],
  },
  // Чек ПРРО
  {
    id: "doc-auto-007",
    number: "ПРРО-2025-00156",
    type: "receipt",
    category: "fiscal",
    title: "Фіскальний чек ПРРО №00156",
    date: getDateInPast(1),
    amount: 8200,
    currency: "UAH",
    status: "signed",
    retentionPeriod: 3,
    createdAt: getDateInPast(1) + "T16:30:00Z",
    createdBy: "system",
    updatedAt: getDateInPast(1) + "T16:30:00Z",
    aiSummary: "Фіскальний чек ПРРО-2025-00156 від " + getDateInPast(1) + ". Оплата готівкою за шиномонтаж на 8 200 ₴. Фіскальний номер зареєстровано в ПРРО.",
  },
  // Рахунок на оплату (невиставлений - контроль)
  {
    id: "doc-auto-008",
    number: "РАХ-2025-018",
    type: "invoice",
    category: "primary",
    title: "Рахунок на ремонт — очікує оплати",
    date: getDateInPast(20),
    dueDate: getDateInPast(5),
    amount: 32000,
    currency: "UAH",
    contractor: { id: "c-auto-6", name: "ТОВ «Логістик»", code: "99887766" },
    status: "sent",
    retentionPeriod: 3,
    createdAt: getDateInPast(20) + "T10:00:00Z",
    createdBy: "owner",
    updatedAt: getDateInPast(20) + "T10:00:00Z",
    aiSummary: "Рахунок РАХ-2025-018 від " + getDateInPast(20) + " для ТОВ «Логістик» (ЄДРПОУ 99887766). Ремонт автомобіля на 32 000 ₴. ПРОСТРОЧЕНО: оплата мала надійти " + getDateInPast(5) + ".",
    aiRisks: [
      {
        id: "r1",
        category: "financial",
        title: "Прострочений рахунок",
        description: "Рахунок прострочений на 5 днів, що може призвести до нарахування пені",
        severity: "high",
        sourceSection: "AI analysis",
        suggestion: {
          text: "Рекомендую терміново зв'язатися з контрагентом для уточнення причин затримки та узгодження нового терміну оплати. Надіслати нагадування про оплату.",
          targetSection: "Умови оплати",
          insertPosition: "append",
          confidence: 94,
        },
      },
    ],
  },
];

// ============================================
// INCOME RECORDS
// ============================================

export const autorepairIncomeRecords: IncomeBookRecord[] = [
  // Касові операції
  {
    id: "inc-auto-001",
    date: getDateInPast(20),
    description: "Ремонт двигуна — готівка",
    contractor: "Фізична особа",
    amount: 12500,
    inIncomeBook: 12500,
    paymentType: "cash",
    source: "prro",
    status: "income",
    txnId: "PRRO-AUTO-001",
  },
  {
    id: "inc-auto-002",
    date: getDateInPast(18),
    description: "Заміна масла — картка",
    contractor: "Фізична особа",
    amount: 2800,
    inIncomeBook: 2800,
    paymentType: "card",
    source: "prro",
    status: "income",
    txnId: "PRRO-AUTO-002",
  },
  {
    id: "inc-auto-003",
    date: getDateInPast(15),
    description: "Страхове замовлення №1234 — СК «АвтоГарант»",
    contractor: "СК «АвтоГарант»",
    contractorCode: "44556677",
    amount: 28500,
    inIncomeBook: 28500,
    paymentType: "bank",
    source: "monobank",
    status: "income",
    txnId: "TXN-AUTO-003",
    documentFlowId: "doc-auto-004",
  },
  {
    id: "inc-auto-004",
    date: getDateInPast(12),
    description: "Діагностика підвіски — готівка",
    contractor: "Фізична особа",
    amount: 1500,
    inIncomeBook: 1500,
    paymentType: "cash",
    source: "prro",
    status: "income",
    txnId: "PRRO-AUTO-003",
  },
  {
    id: "inc-auto-005",
    date: getDateInPast(8),
    description: "Ремонт гальм — картка",
    contractor: "Фізична особа",
    amount: 8500,
    inIncomeBook: 8500,
    paymentType: "card",
    source: "prro",
    status: "income",
    txnId: "PRRO-AUTO-004",
  },
  {
    id: "inc-auto-006",
    date: getDateInPast(5),
    description: "Заміна ременя ГРМ — готівка",
    contractor: "Фізична особа",
    amount: 18000,
    inIncomeBook: 18000,
    paymentType: "cash",
    source: "prro",
    status: "income",
    txnId: "PRRO-AUTO-005",
  },
  {
    id: "inc-auto-007",
    date: getDateInPast(1),
    description: "Шиномонтаж — готівка",
    contractor: "Фізична особа",
    amount: 8200,
    inIncomeBook: 8200,
    paymentType: "cash",
    source: "prro",
    status: "income",
    txnId: "PRRO-AUTO-006",
    documentFlowId: "doc-auto-007",
  },
];

// ============================================
// CONTRACTORS
// ============================================

export const autorepairContractors: Contractor[] = [
  {
    id: "c-auto-1",
    name: "ТОВ «АвтоПарк»",
    code: "22334455",
    type: "legal",
    role: "supplier",
    status: "active",
    balance: -35000,
    tags: ["Оренда", "СТО"],
    paymentTermsDays: 5,
  },
  {
    id: "c-auto-2",
    name: "СК «АвтоГарант»",
    code: "44556677",
    email: "partners@avtogarant.ua",
    type: "legal",
    role: "buyer",
    status: "active",
    balance: 0,
    reliabilityScore: 92,
    activeContractsCount: 1,
    tags: ["Страхова", "B2B"],
  },
  {
    id: "c-auto-3",
    name: "ТОВ «АвтоДеталь»",
    code: "55667788",
    type: "legal",
    role: "supplier",
    status: "active",
    balance: -45000,
    tags: ["Запчастини"],
    paymentTermsDays: 14,
    creditLimit: 100000,
    creditUsed: 45000,
  },
  {
    id: "c-auto-4",
    name: "ФОП Шевченко П.О.",
    code: "6677889900",
    type: "fop",
    role: "supplier",
    status: "active",
    balance: 0,
    taxStatus: "Платник ЄП 2 група",
    tags: ["Комісія"],
  },
  {
    id: "c-auto-5",
    name: "Фізична особа",
    code: "",
    type: "individual",
    role: "buyer",
    status: "active",
    balance: 0,
    tags: ["Роздріб"],
  },
  {
    id: "c-auto-6",
    name: "ТОВ «Логістик»",
    code: "99887766",
    type: "legal",
    role: "buyer",
    status: "active",
    balance: 32000,
    reliabilityScore: 65,
    tags: ["B2B", "Прострочено"],
  },
];

// ============================================
// EMPLOYEES
// ============================================

export const autorepairEmployees: Employee[] = [
  {
    id: "emp-auto-001",
    cabinetId: "demo-autorepair-2",
    fullName: "Сидоренко Петро Михайлович",
    position: "Автомеханік",
    contractType: "labor",
    status: "active",
    startDate: "2023-06-01",
    employmentMode: "full-time",
    fte: 1.0,
    schedule: "Пн-Сб 8:00-17:00",
    location: "office",
    contractNumber: "ТД-2023-003",
    contractDate: "2023-06-01",
    militaryStatus: "liable",
    militaryDocumentDate: "2024-11-15",
    militaryRegistrationNumber: "ВОК-2023-98765",
    history: [
      { date: "2023-06-01", action: "Прийнято на роботу", role: "Власник" },
      { date: "2024-11-15", action: "Оновлено дані військового обліку", role: "Власник" },
    ],
  },
  {
    id: "emp-auto-002",
    cabinetId: "demo-autorepair-2",
    fullName: "Мороз Андрій Ігорович",
    position: "Автоелектрик",
    contractType: "labor",
    status: "probation",
    startDate: "2025-01-10",
    employmentMode: "full-time",
    fte: 1.0,
    schedule: "Пн-Пт 9:00-18:00",
    location: "office",
    contractNumber: "ТД-2025-001",
    contractDate: "2025-01-10",
    militaryStatus: "reserved",
    militaryDocumentDate: "2025-01-08",
    militaryRegistrationNumber: "ВОК-2025-00123",
    history: [
      { date: "2025-01-08", action: "Перевірено бронювання", role: "Власник" },
      { date: "2025-01-10", action: "Прийнято на випробувальний термін", role: "Власник" },
    ],
  },
];

// ============================================
// TAX PAYMENTS
// ============================================

export const autorepairTaxPayments: TaxPayment[] = [
  {
    id: "tax-auto-001",
    cabinetId: "demo-autorepair-2",
    taxType: "ep",
    taxTypeLabel: "ЄП (фікс.)",
    period: "Січень 2025",
    year: 2025,
    month: 1,
    amountToPay: 1600,
    status: "paid",
    statusLabel: "Оплачено",
    deadline: "2025-01-20",
    paidDate: "2025-01-18",
    paidAmount: 1600,
    createdAt: "2025-01-10T08:00:00Z",
  },
  {
    id: "tax-auto-002",
    cabinetId: "demo-autorepair-2",
    taxType: "esv",
    taxTypeLabel: "ЄСВ ФОП",
    period: "Січень 2025",
    year: 2025,
    month: 1,
    amountToPay: 1760,
    status: "paid",
    statusLabel: "Оплачено",
    deadline: "2025-01-20",
    paidDate: "2025-01-18",
    paidAmount: 1760,
    createdAt: "2025-01-10T08:00:00Z",
  },
];

// ============================================
// CONTRACTOR PAYMENTS
// ============================================

export const autorepairContractorPayments: ContractorPayment[] = [
  {
    id: "cp-auto-001",
    cabinetId: "demo-autorepair-2",
    date: getDateFromNow(3),
    contractor: "ТОВ «АвтоПарк»",
    contractorId: "c-auto-1",
    purpose: "Оренда СТО за лютий 2025",
    amount: 35000,
    status: "scheduled",
    statusLabel: "Заплановано",
    paymentPurposeType: "rent",
  },
  {
    id: "cp-auto-002",
    cabinetId: "demo-autorepair-2",
    date: getDateInPast(3),
    contractor: "ТОВ «АвтоДеталь»",
    contractorId: "c-auto-3",
    purpose: "Оплата за запчастини",
    amount: 45000,
    status: "paid",
    statusLabel: "Оплачено",
    paymentPurposeType: "goods",
  },
  {
    id: "cp-auto-003",
    cabinetId: "demo-autorepair-2",
    date: getDateInPast(25),
    contractor: "ТОВ «АвтоПарк»",
    contractorId: "c-auto-1",
    purpose: "Оренда СТО за січень 2025",
    amount: 35000,
    status: "paid",
    statusLabel: "Оплачено",
    paymentPurposeType: "rent",
  },
];

// ============================================
// SALARY PAYMENTS
// ============================================

export const autorepairSalaryPayments: SalaryPayment[] = [
  {
    id: "sal-auto-001",
    cabinetId: "demo-autorepair-2",
    employeeId: "emp-auto-001",
    employeeName: "Сидоренко Петро Михайлович",
    employeePosition: "Автомеханік",
    salaryType: "salary",
    salaryTypeLabel: "Заробітна плата",
    period: "Січень 2025",
    amount: 21000,
    status: "paid",
    statusLabel: "Оплачено",
    scheduledDate: "2025-02-07",
    paidDate: "2025-02-07",
    source: "payroll",
    grossAmount: 30000,
    netAmount: 21000,
    pdfoAmount: 5400,
    militaryTaxAmount: 1500,
    esvAmount: 6600,
  },
  {
    id: "sal-auto-002",
    cabinetId: "demo-autorepair-2",
    employeeId: "emp-auto-002",
    employeeName: "Мороз Андрій Ігорович",
    employeePosition: "Автоелектрик",
    salaryType: "salary",
    salaryTypeLabel: "Заробітна плата",
    period: "Січень 2025",
    amount: 16800,
    status: "paid",
    statusLabel: "Оплачено",
    scheduledDate: "2025-02-07",
    paidDate: "2025-02-07",
    source: "payroll",
    grossAmount: 24000,
    netAmount: 16800,
    pdfoAmount: 4320,
    militaryTaxAmount: 1200,
    esvAmount: 5280,
  },
];

// ============================================
// REPORTS
// ============================================

export const autorepairReports: Report[] = [
  {
    id: "rep-auto-ep-2024",
    cabinetId: "demo-autorepair-2",
    type: "ep",
    typeLabel: "ЄП",
    name: "Декларація ЄП за 2024 рік",
    period: "year",
    periodLabel: "2024 рік",
    year: 2024,
    deadline: "2025-03-01",
    status: "accepted" as ReportStatus,
    statusLabel: "Прийнято",
    submittedDate: "2025-02-25",
    acceptedDate: "2025-02-26",
    dataSources: ["income-book"],
    fopGroup: 2,
    formCode: "F0103406",
    history: [
      { date: "2025-02-20", action: "Сформовано" },
      { date: "2025-02-25", action: "Подано через Дія" },
      { date: "2025-02-26", action: "Прийнято ДПС" },
    ],
  },
  {
    id: "rep-auto-esv-2024",
    cabinetId: "demo-autorepair-2",
    type: "esv",
    typeLabel: "ЄСВ",
    name: "Звіт з ЄСВ за 2024 рік",
    period: "year",
    periodLabel: "2024 рік",
    year: 2024,
    deadline: "2025-03-01",
    status: "accepted" as ReportStatus,
    statusLabel: "Прийнято",
    submittedDate: "2025-02-25",
    acceptedDate: "2025-02-26",
    amountToPay: 0,
    dataSources: ["income-book"],
    fopGroup: 2,
    formCode: "F0133108",
    history: [],
  },
  {
    id: "rep-auto-ep-2025",
    cabinetId: "demo-autorepair-2",
    type: "ep",
    typeLabel: "ЄП",
    name: "Декларація ЄП за 2025 рік",
    period: "year",
    periodLabel: "2025 рік",
    year: 2025,
    deadline: "2026-03-01",
    status: "scheduled" as ReportStatus,
    statusLabel: "Заплановано",
    dataSources: ["income-book"],
    fopGroup: 2,
    formCode: "F0103406",
    history: [],
  },
  {
    id: "rep-auto-1df-jan-2025",
    cabinetId: "demo-autorepair-2",
    type: "1df",
    typeLabel: "Податковий розрахунок (4ДФ)",
    name: "Податковий розрахунок (4ДФ) за січень 2025",
    period: "month",
    periodLabel: "Січень 2025",
    year: 2025,
    month: 1,
    deadline: "2025-02-20",
    status: "accepted" as ReportStatus,
    statusLabel: "Прийнято",
    submittedDate: "2025-02-19",
    acceptedDate: "2025-02-20",
    dataSources: ["employees"],
    fopGroup: 2,
    formCode: "F0500107",
    history: [],
  },
];
