/**
 * CONSULTING CABINET (demo-consulting-3)
 * ФОП Шевченко М.О. — Консалтинг, 3 група, 3 працівники
 */

import type { Document } from "@/config/documentFlowConfig";
import type { IncomeBookRecord } from "@/config/incomeBookConfig";
import type { TaxPayment, ContractorPayment, SalaryPayment } from "@/config/paymentsConfig";
import type { Contractor } from "@/config/settingsConfig";
import type { Employee } from "@/config/employeesConfig";
import type { Report, ReportStatus } from "@/config/reportsConfig";
import { getDateFromNow, getDateInPast } from "./helpers";

// ============================================
// DOCUMENTS
// ============================================

// Cabinet identity for all Consulting documents
const CONSULTING_CABINET = {
  cabinetId: "demo-consulting-3",
  cabinetName: "ФОП Шевченко М.О.",
  cabinetCode: "3112345678",
};

export const consultingDocuments: Document[] = [
  // Контракти з клієнтами (ретейнери)
  {
    id: "doc-cons-001",
    ...CONSULTING_CABINET,
    number: "КОН-2025-001",
    type: "contract",
    category: "contract",
    title: "Договір консалтингових послуг з ТОВ «АльфаГруп»",
    date: "2025-01-15",
    dueDate: "2026-01-15",
    amount: 75000,
    currency: "UAH",
    contractor: { id: "c-cons-1", name: "ТОВ «АльфаГруп»", code: "12345678" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-01-15T10:00:00Z",
    createdBy: "owner",
    updatedAt: "2025-01-15T10:00:00Z",
    aiSummary: "Договір на консалтингові послуги з питань управління на суму 75 000 ₴/міс. Клієнт — ТОВ «АльфаГруп». Термін дії: 15.01.2025 — 15.01.2026. Передбачена автопролонгація.",
    // Template-based fieldValues for unified display
    templateId: "sys-contract-services",
    fieldValues: {
      documentNumber: "КОН-2025-001",
      documentDate: "2025-01-15",
      executorName: "ФОП Шевченко Михайло Олександрович",
      executorCode: "3112345678",
      customerName: "ТОВ «АльфаГруп»",
      customerCode: "12345678",
      subject: "Консалтингові послуги з питань управління",
      total: "75000",
      validFrom: "2025-01-15",
      validTo: "2026-01-15",
    },
    aiRisks: [
      {
        id: "r-cons-001-1",
        category: "deadline",
        title: "Автопролонгація без контролю",
        description: "Договір автоматично продовжується. Рекомендуємо встановити нагадування.",
        severity: "medium",
        sourceSection: "п. 9.2 «Термін дії»",
        suggestion: {
          text: "Рекомендую встановити нагадування за 30 днів до 15.01.2026 для прийняття рішення про пролонгацію або розірвання договору.",
          targetSection: "Термін дії",
          insertPosition: "append",
          confidence: 88,
        },
      },
    ],
  },
  {
    id: "doc-cons-002",
    ...CONSULTING_CABINET,
    number: "КОН-2025-002",
    type: "contract",
    category: "contract",
    title: "Договір про надання послуг з ТОВ «БетаСофт»",
    date: "2025-02-01",
    dueDate: "2025-12-31",
    amount: 120000,
    currency: "UAH",
    contractor: { id: "c-cons-2", name: "ТОВ «БетаСофт»", code: "87654321" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-02-01T09:00:00Z",
    createdBy: "owner",
    updatedAt: "2025-02-01T09:00:00Z",
    aiSummary: "Аутсорсинг HR-консалтингу для IT-компанії ТОВ «БетаСофт» на суму 120 000 ₴/міс. Термін дії договору: до 31.12.2025.",
    aiRisks: [
      {
        id: "r-cons-002-1",
        category: "legal",
        title: "Відсутня NDA",
        description: "Договір з IT-компанією без угоди про конфіденційність може призвести до витоку інформації.",
        severity: "low",
        sourceSection: "Загальні положення",
        suggestion: {
          text: "Рекомендую укласти окрему Угоду про нерозголошення (NDA) або додати розділ про конфіденційність до договору.",
          targetSection: "Розділ «Конфіденційність»",
          insertPosition: "append",
          confidence: 75,
        },
      },
    ],
  },
  {
    id: "doc-cons-003",
    ...CONSULTING_CABINET,
    number: "КОН-2025-003",
    type: "contract",
    category: "contract",
    title: "Договір консультування з ФОП Мельник О.В.",
    date: "2025-03-01",
    dueDate: "2025-08-31",
    amount: 45000,
    currency: "UAH",
    contractor: { id: "c-cons-3", name: "ФОП Мельник О.В.", code: "3456789012" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-03-01T11:00:00Z",
    createdBy: "owner",
    updatedAt: "2025-03-01T11:00:00Z",
    aiSummary: "Договір на бізнес-консультування з ФОП Мельник О.В. на суму 45 000 ₴/міс. Термін дії: 01.03.2025 — 31.08.2025.",
    aiRisks: [
      {
        id: "r-cons-003-1",
        category: "counterparty",
        title: "Контрагент — ФОП",
        description: "Робота з ФОП вимагає перевірки статусу платника ЄП та уникнення ознак трудових відносин.",
        severity: "low",
        sourceSection: "Сторони договору",
        suggestion: {
          text: "Перевірте актуальність реєстрації ФОП Мельник О.В. в реєстрі платників ЄП. Переконайтесь у відсутності ознак трудових відносин.",
          targetSection: "Реквізити",
          insertPosition: "append",
          confidence: 82,
        },
      },
    ],
  },
  // Акти виконаних робіт
  {
    id: "doc-cons-004",
    ...CONSULTING_CABINET,
    number: "АКТ-2025-001",
    type: "act",
    category: "primary",
    title: "Акт надання послуг за січень 2025",
    date: getDateInPast(15),
    amount: 75000,
    currency: "UAH",
    contractor: { id: "c-cons-1", name: "ТОВ «АльфаГруп»", code: "12345678" },
    status: "signed",
    retentionPeriod: 3,
    createdAt: getDateInPast(15) + "T12:00:00Z",
    createdBy: "owner",
    updatedAt: getDateInPast(14) + "T10:00:00Z",
    linkedDocuments: ["doc-cons-001"],
    aiSummary: "Акт виконаних робіт з консалтингових послуг за січень 2025 на суму 75 000 ₴. Замовник — ТОВ «АльфаГруп». Підписано обома сторонами.",
    // Template-based fieldValues for unified display
    templateId: "sys-act-standard",
    fieldValues: {
      documentNumber: "АКТ-2025-001",
      documentDate: getDateInPast(15),
      total: "75000",
      executorName: "ФОП Шевченко Михайло Олександрович",
      executorCode: "3112345678",
      customerName: "ТОВ «АльфаГруп»",
      customerCode: "12345678",
      subject: "Надання консалтингових послуг з управління за січень 2025",
    },
  },
  {
    id: "doc-cons-005",
    ...CONSULTING_CABINET,
    number: "АКТ-2025-002",
    type: "act",
    category: "primary",
    title: "Акт надання послуг за січень 2025 (БетаСофт)",
    date: getDateInPast(12),
    amount: 120000,
    currency: "UAH",
    contractor: { id: "c-cons-2", name: "ТОВ «БетаСофт»", code: "87654321" },
    status: "signed",
    retentionPeriod: 3,
    createdAt: getDateInPast(12) + "T14:00:00Z",
    createdBy: "owner",
    updatedAt: getDateInPast(11) + "T09:00:00Z",
    aiSummary: "Акт виконаних робіт з HR-консалтингу за січень 2025 на суму 120 000 ₴. Замовник — ТОВ «БетаСофт». Підписано обома сторонами.",
  },
  // ВХІДНИЙ документ для акту розбіжностей
  {
    id: "doc-cons-006",
    ...CONSULTING_CABINET,
    number: "РАХ-IN-2025-001",
    type: "invoice",
    category: "primary",
    title: "Рахунок від постачальника канцтоварів",
    date: getDateInPast(5),
    amount: 8500,
    currency: "UAH",
    contractor: { id: "c-cons-5", name: "ТОВ «ОфісМаркет»", code: "34567890" },
    status: "sent",
    retentionPeriod: 3,
    createdAt: getDateInPast(5) + "T10:00:00Z",
    createdBy: "contractor",
    updatedAt: getDateInPast(5) + "T10:00:00Z",
    aiSummary: "Вхідний рахунок на канцтовари від ТОВ «ОфісМаркет» на суму 8 500 ₴. Потребує оплати та віднесення до витрат.",
    aiRisks: [
      {
        id: "r-cons-006-1",
        category: "financial",
        title: "Перевірте призначення платежу",
        description: "Вхідний рахунок — уточніть статтю витрат для коректного обліку.",
        severity: "low",
        sourceSection: "Призначення платежу",
        suggestion: {
          text: "Віднесіть витрату до категорії «Адміністративні витрати» або «Канцтовари» для правильного податкового обліку.",
          targetSection: "Призначення",
          insertPosition: "append",
          confidence: 78,
        },
      },
    ],
  },
  // Грантовий договір (not-income)
  {
    id: "doc-cons-007",
    ...CONSULTING_CABINET,
    number: "ГРАНТ-2025-001",
    type: "contract",
    category: "contract",
    title: "Грантова угода з USAID",
    date: "2025-01-01",
    dueDate: "2025-12-31",
    amount: 250000,
    currency: "UAH",
    contractor: { id: "c-cons-6", name: "USAID Ukraine", code: "00000001" },
    status: "signed",
    retentionPeriod: 7,
    createdAt: "2025-01-01T08:00:00Z",
    createdBy: "contractor",
    updatedAt: "2025-01-10T14:00:00Z",
    aiSummary: "Грантова угода на розвиток консалтингових програм на суму 250 000 ₴. Важливо: грантові кошти НЕ є доходом ФОП та не враховуються в ліміт єдиного податку.",
    tags: ["грант", "not-income", "USAID"],
    aiRisks: [
      {
        id: "r-cons-007-1",
        category: "compliance",
        title: "Грант НЕ є доходом ФОП",
        description: "Важливо: грантові кошти не враховуються в ліміт єдиного податку.",
        severity: "low",
        sourceSection: "Загальні положення",
        suggestion: {
          text: "Переконайтесь, що сума 250 000 грн не враховується в Книгу обліку доходів. Позначте всі надходження за цим договором як «not-income».",
          targetSection: "Облік",
          insertPosition: "append",
          confidence: 95,
        },
      },
    ],
  },
  // Анкета фінансового моніторингу
  {
    id: "doc-cons-008",
    ...CONSULTING_CABINET,
    number: "ФІНМОН-2025-001",
    type: "other",
    category: "internal",
    title: "Анкета фінансового моніторингу — ТОВ «АльфаГруп»",
    date: "2025-01-20",
    currency: "UAH",
    contractor: { id: "c-cons-1", name: "ТОВ «АльфаГруп»", code: "12345678" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-01-20T15:00:00Z",
    createdBy: "owner",
    updatedAt: "2025-01-20T15:00:00Z",
    aiSummary: "Заповнена анкета фінансового моніторингу для клієнта ТОВ «АльфаГруп» згідно вимог ДСФМУ. Внутрішній документ.",
  },
  // Договір оренди офісу
  {
    id: "doc-cons-009",
    ...CONSULTING_CABINET,
    number: "ОРЕНДА-2025-001",
    type: "rental-agreement",
    category: "contract",
    title: "Договір оренди офісу",
    date: "2025-01-01",
    dueDate: "2025-12-31",
    amount: 25000,
    currency: "UAH",
    contractor: { id: "c-cons-7", name: "ТОВ «БізнесЦентр»", code: "11223344" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-01-01T08:00:00Z",
    createdBy: "contractor",
    updatedAt: "2025-01-01T12:00:00Z",
    aiSummary: "Договір оренди офісного приміщення (50 м²) за 25 000 ₴/міс. Орендодавець — ТОВ «БізнесЦентр». Термін дії: до 31.12.2025.",
    // Template-based fieldValues for unified display
    templateId: "sys-contract-rental",
    fieldValues: {
      documentNumber: "ОРЕНДА-2025-001",
      documentDate: "2025-01-01",
      landlordName: "ТОВ «БізнесЦентр»",
      landlordCode: "11223344",
      tenantName: "ФОП Шевченко Михайло Олександрович",
      tenantCode: "3112345678",
      rentalObject: "Офісне приміщення, 50 м²",
      monthlyRent: "25000",
      validTo: "2025-12-31",
    },
    aiRisks: [
      {
        id: "r-cons-009-1",
        category: "deadline",
        title: "Наближення терміну пролонгації",
        description: "Термін дії договору оренди закінчується 31.12.2025. Прийміть рішення щодо продовження.",
        severity: "medium",
        sourceSection: "п. 7.1 «Термін дії»",
        suggestion: {
          text: "Рекомендую розпочати переговори з орендодавцем за 60 днів до закінчення терміну. Перегляньте умови індексації орендної плати.",
          targetSection: "Термін дії",
          insertPosition: "append",
          confidence: 90,
        },
      },
    ],
  },
  // Рахунки (invoices)
  {
    id: "doc-cons-010",
    ...CONSULTING_CABINET,
    number: "РАХ-2025-001",
    type: "invoice",
    category: "primary",
    title: "Рахунок на оплату за лютий — ТОВ «АльфаГруп»",
    date: getDateInPast(3),
    dueDate: getDateFromNow(14),
    amount: 75000,
    currency: "UAH",
    contractor: { id: "c-cons-1", name: "ТОВ «АльфаГруп»", code: "12345678" },
    status: "sent",
    retentionPeriod: 3,
    createdAt: getDateInPast(3) + "T10:00:00Z",
    createdBy: "owner",
    updatedAt: getDateInPast(3) + "T10:00:00Z",
    aiSummary: "Рахунок на консалтингові послуги за лютий 2025 на суму 75 000 ₴. Платник — ТОВ «АльфаГруп». Очікується оплата.",
    // Template-based fieldValues for unified display
    templateId: "sys-invoice-standard",
    fieldValues: {
      documentNumber: "РАХ-2025-001",
      documentDate: getDateInPast(3),
      total: "75000",
      supplierName: "ФОП Шевченко Михайло Олександрович",
      supplierCode: "3112345678",
      buyerName: "ТОВ «АльфаГруп»",
      buyerCode: "12345678",
      subject: "Консалтингові послуги за лютий 2025",
    },
    aiRisks: [
      {
        id: "r-cons-010-1",
        category: "financial",
        title: "Контролюйте термін оплати",
        description: "Рахунок відправлено — відстежуйте надходження коштів до дедлайну.",
        severity: "low",
        sourceSection: "Умови оплати",
        suggestion: {
          text: "Якщо оплата не надійде протягом 3 робочих днів після дедлайну, надішліть контрагенту ввічливе нагадування.",
          targetSection: "Умови оплати",
          insertPosition: "append",
          confidence: 80,
        },
      },
    ],
  },
];

// ============================================
// INCOME RECORDS
// ============================================

export const consultingIncomeRecords: IncomeBookRecord[] = [
  {
    id: "inc-cons-001",
    date: "2025-01-15",
    description: "Оплата за консалтинг — ТОВ «АльфаГруп»",
    contractor: "ТОВ «АльфаГруп»",
    contractorCode: "12345678",
    contractorIban: "UA213223130000026007233566001",
    amount: 75000,
    inIncomeBook: 75000,
    paymentType: "bank",
    source: "monobank",
    status: "income",
    txnId: "TXN-CONS-001",
    documentFlowId: "doc-cons-004",
  },
  {
    id: "inc-cons-002",
    date: "2025-01-20",
    description: "Оплата за HR-консалтинг — ТОВ «БетаСофт»",
    contractor: "ТОВ «БетаСофт»",
    contractorCode: "87654321",
    amount: 120000,
    inIncomeBook: 120000,
    paymentType: "bank",
    source: "monobank",
    status: "income",
    txnId: "TXN-CONS-002",
  },
  // ГРАНТ — не дохід!
  {
    id: "inc-cons-003",
    date: "2025-01-25",
    description: "Грант USAID — перший транш",
    contractor: "USAID Ukraine",
    contractorCode: "00000001",
    amount: 125000,
    inIncomeBook: 0,
    paymentType: "bank",
    source: "monobank",
    status: "not-income",
    txnId: "TXN-GRANT-001",
    aiNote: "Грантові кошти не є доходом ФОП згідно пп. 165.1.1 ПКУ",
    documentFlowId: "doc-cons-007",
  },
  {
    id: "inc-cons-004",
    date: "2025-02-10",
    description: "Оплата за консалтинг лютий — ТОВ «АльфаГруп»",
    contractor: "ТОВ «АльфаГруп»",
    contractorCode: "12345678",
    amount: 75000,
    inIncomeBook: 75000,
    paymentType: "bank",
    source: "monobank",
    status: "income",
    txnId: "TXN-CONS-004",
  },
  {
    id: "inc-cons-005",
    date: "2025-02-15",
    description: "Оплата за HR-консалтинг лютий — ТОВ «БетаСофт»",
    contractor: "ТОВ «БетаСофт»",
    contractorCode: "87654321",
    amount: 120000,
    inIncomeBook: 120000,
    paymentType: "bank",
    source: "monobank",
    status: "income",
    txnId: "TXN-CONS-005",
  },
  {
    id: "inc-cons-006",
    date: "2025-02-20",
    description: "ФОП Мельник — консультування",
    contractor: "ФОП Мельник О.В.",
    contractorCode: "3456789012",
    amount: 45000,
    inIncomeBook: 45000,
    paymentType: "bank",
    source: "privat24",
    status: "income",
    txnId: "TXN-CONS-006",
  },
  // Ще один транш гранту
  {
    id: "inc-cons-007",
    date: "2025-02-28",
    description: "Грант USAID — другий транш",
    contractor: "USAID Ukraine",
    contractorCode: "00000001",
    amount: 125000,
    inIncomeBook: 0,
    paymentType: "bank",
    source: "monobank",
    status: "not-income",
    txnId: "TXN-GRANT-002",
    aiNote: "Грантові кошти не враховуються в ліміт ФОП",
  },
];

// ============================================
// CONTRACTORS
// ============================================

export const consultingContractors: Contractor[] = [
  {
    id: "c-cons-1",
    name: "ТОВ «АльфаГруп»",
    code: "12345678",
    email: "office@alfagroup.ua",
    type: "legal",
    role: "buyer",
    status: "active",
    balance: 0,
    reliabilityScore: 95,
    activeContractsCount: 1,
    tags: ["VIP", "Регулярний"],
    paymentTermsDays: 10,
  },
  {
    id: "c-cons-2",
    name: "ТОВ «БетаСофт»",
    code: "87654321",
    email: "hr@betasoft.io",
    type: "legal",
    role: "buyer",
    status: "active",
    balance: 0,
    reliabilityScore: 88,
    activeContractsCount: 1,
    tags: ["IT", "HR"],
    paymentTermsDays: 15,
  },
  {
    id: "c-cons-3",
    name: "ФОП Мельник О.В.",
    code: "3456789012",
    type: "fop",
    role: "buyer",
    status: "active",
    balance: 0,
    taxStatus: "Платник ЄП 3 група",
    tags: ["Разовий"],
  },
  {
    id: "c-cons-5",
    name: "ТОВ «ОфісМаркет»",
    code: "34567890",
    type: "legal",
    role: "supplier",
    status: "active",
    balance: -8500,
    tags: ["Канцтовари"],
  },
  {
    id: "c-cons-6",
    name: "USAID Ukraine",
    code: "00000001",
    type: "legal",
    role: "supplier",
    status: "active",
    balance: 0,
    tags: ["Грант", "Міжнародний"],
  },
  {
    id: "c-cons-7",
    name: "ТОВ «БізнесЦентр»",
    code: "11223344",
    type: "legal",
    role: "supplier",
    status: "active",
    balance: -25000,
    tags: ["Оренда"],
    paymentTermsDays: 5,
  },
];

// ============================================
// EMPLOYEES
// ============================================

export const consultingEmployees: Employee[] = [
  {
    id: "emp-cons-001",
    cabinetId: "demo-consulting-3",
    fullName: "Левченко Ольга Андріївна",
    position: "Старший консультант",
    contractType: "labor",
    status: "active",
    startDate: "2024-03-01",
    employmentMode: "full-time",
    fte: 1.0,
    schedule: "Пн-Пт 9:00-18:00",
    location: "hybrid",
    contractNumber: "ТД-2024-001",
    contractDate: "2024-03-01",
    militaryStatus: "not-applicable",
    history: [
      { date: "2024-03-01", action: "Прийнято на роботу", role: "Власник" },
      { date: "2024-06-01", action: "Пройшов випробувальний термін", role: "Система" },
    ],
  },
  {
    id: "emp-cons-002",
    cabinetId: "demo-consulting-3",
    fullName: "Павленко Ігор Васильович",
    position: "Консультант",
    contractType: "labor",
    status: "active",
    startDate: "2024-09-01",
    employmentMode: "full-time",
    fte: 1.0,
    schedule: "Пн-Пт 9:00-18:00",
    location: "remote",
    contractNumber: "ТД-2024-005",
    contractDate: "2024-09-01",
    militaryStatus: "reserved",
    militaryDocumentDate: "2025-01-10",
    militaryRegistrationNumber: "ВОК-2024-12345",
    history: [
      { date: "2024-09-01", action: "Прийнято на роботу", role: "Власник" },
      { date: "2024-12-01", action: "Пройшов випробувальний термін", role: "Система" },
      { date: "2025-01-10", action: "Оформлено бронювання", role: "Власник" },
    ],
  },
  {
    id: "emp-cons-003",
    cabinetId: "demo-consulting-3",
    fullName: "Кравець Марина Олегівна",
    position: "Адміністратор",
    contractType: "civil",
    status: "active",
    startDate: "2025-01-15",
    employmentMode: "part-time",
    fte: 0.5,
    schedule: "Пн-Ср 10:00-16:00",
    location: "office",
    contractNumber: "ЦПД-2025-001",
    contractDate: "2025-01-15",
    militaryStatus: "not-applicable",
    comments: "Адміністративна підтримка, документообіг",
    history: [
      { date: "2025-01-15", action: "Укладено ЦПД", role: "Власник" },
    ],
  },
];

// ============================================
// TAX PAYMENTS
// ============================================

export const consultingTaxPayments: TaxPayment[] = [
  {
    id: "tax-cons-001",
    cabinetId: "demo-consulting-3",
    taxType: "ep",
    taxTypeLabel: "ЄП",
    period: "І квартал 2025",
    year: 2025,
    quarter: 1,
    amountToPay: 37500,
    status: "paid",
    statusLabel: "Оплачено",
    deadline: "2025-04-19",
    paidDate: "2025-04-15",
    paidAmount: 37500,
    createdAt: "2025-04-01T08:00:00Z",
    calculatedFromIncome: 750000,
    taxRate: 5,
  },
  {
    id: "tax-cons-002",
    cabinetId: "demo-consulting-3",
    taxType: "esv",
    taxTypeLabel: "ЄСВ ФОП",
    period: "І квартал 2025",
    year: 2025,
    quarter: 1,
    amountToPay: 5280,
    status: "paid",
    statusLabel: "Оплачено",
    deadline: "2025-04-19",
    paidDate: "2025-04-15",
    paidAmount: 5280,
    createdAt: "2025-04-01T08:00:00Z",
  },
];

// ============================================
// CONTRACTOR PAYMENTS
// ============================================

export const consultingContractorPayments: ContractorPayment[] = [
  {
    id: "cp-cons-001",
    cabinetId: "demo-consulting-3",
    date: getDateInPast(5),
    contractor: "ТОВ «БізнесЦентр»",
    contractorId: "c-cons-7",
    contractorCode: "11223344",
    purpose: "Оренда офісу за лютий 2025",
    amount: 25000,
    status: "paid",
    statusLabel: "Оплачено",
    paymentPurposeType: "rent",
    contractNumber: "ОРЕНДА-2025-001",
  },
  {
    id: "cp-cons-002",
    cabinetId: "demo-consulting-3",
    date: getDateFromNow(5),
    contractor: "ТОВ «БізнесЦентр»",
    contractorId: "c-cons-7",
    purpose: "Оренда офісу за березень 2025",
    amount: 25000,
    status: "scheduled",
    statusLabel: "Заплановано",
    paymentPurposeType: "rent",
  },
  {
    id: "cp-cons-003",
    cabinetId: "demo-consulting-3",
    date: getDateInPast(3),
    contractor: "ТОВ «ОфісМаркет»",
    contractorId: "c-cons-5",
    purpose: "Канцтовари та витратні матеріали",
    amount: 8500,
    status: "paid",
    statusLabel: "Оплачено",
    paymentPurposeType: "goods",
  },
];

// ============================================
// SALARY PAYMENTS
// ============================================

export const consultingSalaryPayments: SalaryPayment[] = [
  {
    id: "sal-cons-001",
    cabinetId: "demo-consulting-3",
    employeeId: "emp-cons-001",
    employeeName: "Левченко Ольга Андріївна",
    employeePosition: "Старший консультант",
    salaryType: "salary",
    salaryTypeLabel: "Заробітна плата",
    period: "Січень 2025",
    amount: 35000,
    status: "paid",
    statusLabel: "Оплачено",
    scheduledDate: "2025-02-07",
    paidDate: "2025-02-07",
    source: "payroll",
    grossAmount: 50000,
    netAmount: 35000,
    pdfoAmount: 9000,
    militaryTaxAmount: 2500,
    esvAmount: 11000,
  },
  {
    id: "sal-cons-002",
    cabinetId: "demo-consulting-3",
    employeeId: "emp-cons-002",
    employeeName: "Павленко Ігор Васильович",
    employeePosition: "Консультант",
    salaryType: "salary",
    salaryTypeLabel: "Заробітна плата",
    period: "Січень 2025",
    amount: 28000,
    status: "paid",
    statusLabel: "Оплачено",
    scheduledDate: "2025-02-07",
    paidDate: "2025-02-07",
    source: "payroll",
    grossAmount: 40000,
    netAmount: 28000,
    pdfoAmount: 7200,
    militaryTaxAmount: 2000,
    esvAmount: 8800,
  },
];

// ============================================
// REPORTS
// ============================================

export const consultingReports: Report[] = [
  {
    id: "rep-cons-ep-q1-2025",
    cabinetId: "demo-consulting-3",
    type: "ep",
    typeLabel: "ЄП",
    name: "Декларація ЄП за І квартал 2025",
    period: "Q1",
    periodLabel: "І квартал 2025",
    year: 2025,
    quarter: 1,
    deadline: "2025-05-09",
    status: "review" as ReportStatus,
    statusLabel: "На перевірку",
    draftProgress: 85,
    amountToPay: 37500,
    dataSources: ["income-book"],
    fopGroup: 3,
    formCode: "F0103308",
    history: [
      { date: "2025-04-01", action: "Автоматично сформовано AI" },
    ],
  },
  {
    id: "rep-cons-esv-q1-2025",
    cabinetId: "demo-consulting-3",
    type: "esv",
    typeLabel: "ЄСВ",
    name: "Звіт з ЄСВ за І квартал 2025",
    period: "Q1",
    periodLabel: "І квартал 2025",
    year: 2025,
    quarter: 1,
    deadline: "2025-05-09",
    status: "scheduled" as ReportStatus,
    statusLabel: "Заплановано",
    amountToPay: 5808,
    dataSources: ["income-book"],
    fopGroup: 3,
    formCode: "F0133108",
    history: [],
  },
  {
    id: "rep-cons-1df-jan-2025",
    cabinetId: "demo-consulting-3",
    type: "1df",
    typeLabel: "Податковий розрахунок (4ДФ)",
    name: "Податковий розрахунок (4ДФ) за січень 2025",
    period: "month",
    periodLabel: "Січень 2025",
    year: 2025,
    month: 1,
    deadline: "2025-02-20",
    status: "accepted" as ReportStatus,
    statusLabel: "Прийнято",
    submittedDate: "2025-02-18",
    acceptedDate: "2025-02-19",
    dataSources: ["employees"],
    fopGroup: 3,
    formCode: "F0500107",
    history: [
      { date: "2025-02-15", action: "Сформовано" },
      { date: "2025-02-18", action: "Подано через Кабінет ДПС" },
      { date: "2025-02-19", action: "Прийнято ДПС" },
    ],
  },
  {
    id: "rep-cons-1df-feb-2025",
    cabinetId: "demo-consulting-3",
    type: "1df",
    typeLabel: "Податковий розрахунок (4ДФ)",
    name: "Податковий розрахунок (4ДФ) за лютий 2025",
    period: "month",
    periodLabel: "Лютий 2025",
    year: 2025,
    month: 2,
    deadline: "2025-03-20",
    status: "review" as ReportStatus,
    statusLabel: "На перевірку",
    draftProgress: 100,
    dataSources: ["employees"],
    fopGroup: 3,
    formCode: "F0500107",
    history: [
      { date: "2025-03-10", action: "Автоматично сформовано AI" },
    ],
  },
];
