/**
 * DEALER CABINET (demo-dealer-2)
 * ФОП Кравченко О.П. — Дилер, 2 група, 1 працівник
 */

import type { Document } from "@/config/documentFlowConfig";
import type { IncomeBookRecord } from "@/config/incomeBookConfig";
import type { TaxPayment, ContractorPayment, SalaryPayment } from "@/config/paymentsConfig";
import type { Contractor } from "@/config/settingsConfig";
import type { Employee } from "@/config/employeesConfig";
import type { Report, ReportStatus } from "@/config/reportsConfig";
import { getDateFromNow, getDateInPast } from "./helpers";

// Cabinet identity for all Dealer documents
const DEALER_CABINET = {
  cabinetId: "demo-dealer-2",
  cabinetName: "ФОП Кравченко О.П.",
  cabinetCode: "4455667788",
};

// ============================================
// DOCUMENTS
// ============================================

export const dealerDocuments: Document[] = [
  // Дилерський договір з виробником
  {
    id: "doc-deal-001",
    ...DEALER_CABINET,
    number: "ДИЛЕР-2025-001",
    type: "contract",
    category: "contract",
    title: "Дилерський договір з ТОВ «ВиробникПлюс»",
    date: "2025-01-01",
    dueDate: "2025-12-31",
    currency: "UAH",
    contractor: { id: "c-deal-1", name: "ТОВ «ВиробникПлюс»", code: "11112222" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-01-01T08:00:00Z",
    createdBy: "contractor",
    updatedAt: "2025-01-05T10:00:00Z",
    aiSummary: "Дилерський договір на поставку товарів від ТОВ «ВиробникПлюс». Націнка 15-25%. Відтермінування оплати 30 днів. Термін дії: до 31.12.2025.",
    // Template-based fieldValues for unified display
    templateId: "sys-supply-contract",
    fieldValues: {
      documentNumber: "ДИЛЕР-2025-001",
      documentDate: "2025-01-01",
      supplierName: "ТОВ «ВиробникПлюс»",
      supplierCode: "11112222",
      buyerName: "ФОП Кравченко О.П.",
      buyerCode: "4455667788",
      subject: "Дилерський договір на поставку товарів з націнкою 15-25%",
      deliveryTerms: "Відтермінування оплати 30 днів",
      validTo: "2025-12-31",
    },
    aiRisks: [
      {
        id: "r-deal-001-1",
        category: "financial",
        title: "Націнка 15-25% не зафіксована",
        description: "Діапазон націнки занадто широкий — може призвести до спорів щодо ціноутворення.",
        severity: "medium",
        sourceSection: "п. 5.2 «Ціноутворення»",
        suggestion: {
          text: "Рекомендую закріпити мінімальну націнку 15% у додатку до договору для захисту маржі.",
          targetSection: "Ціноутворення",
          insertPosition: "append",
          confidence: 84,
        },
      },
    ],
  },
  // Накладна від постачальника
  {
    id: "doc-deal-002",
    ...DEALER_CABINET,
    number: "ТТН-2025-0045",
    type: "ttn",
    category: "primary",
    title: "ТТН на поставку товару партія №45",
    date: getDateInPast(3),
    amount: 185000,
    currency: "UAH",
    contractor: { id: "c-deal-1", name: "ТОВ «ВиробникПлюс»", code: "11112222" },
    status: "confirmed",
    retentionPeriod: 3,
    createdAt: getDateInPast(3) + "T08:00:00Z",
    createdBy: "contractor",
    updatedAt: getDateInPast(2) + "T14:00:00Z",
    linkedDocuments: ["doc-deal-001"],
    aiSummary: "Товарно-транспортна накладна на партію товару №45 на суму 185 000 ₴ від ТОВ «ВиробникПлюс». Товар прийнято на склад.",
    // Template-based fieldValues for unified display
    templateId: "sys-ttn-standard",
    fieldValues: {
      documentNumber: "ТТН-2025-0045",
      documentDate: getDateInPast(3),
      total: "185000",
      supplierName: "ТОВ «ВиробникПлюс»",
      supplierCode: "11112222",
      buyerName: "ФОП Кравченко О.П.",
      buyerCode: "4455667788",
      subject: "Партія товару №45",
    },
    aiRisks: [
      {
        id: "r-deal-002-1",
        category: "financial",
        title: "Перевірте комплектність поставки",
        description: "При прийманні великої партії на 185 000 грн звірте кількість з накладною.",
        severity: "low",
        sourceSection: "Комплектація",
        suggestion: {
          text: "Порівняйте фактичну кількість товару з даними ТТН. При розбіжностях — складіть акт невідповідності.",
          targetSection: "Приймання",
          insertPosition: "append",
          confidence: 76,
        },
      },
    ],
  },
  // Договір з покупцем B2B
  {
    id: "doc-deal-003",
    ...DEALER_CABINET,
    number: "ПОК-2025-001",
    type: "supply-contract",
    category: "contract",
    title: "Договір поставки з ТОВ «МагазинОпт»",
    date: "2025-01-15",
    dueDate: "2025-12-31",
    currency: "UAH",
    contractor: { id: "c-deal-2", name: "ТОВ «МагазинОпт»", code: "33334444" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-01-15T10:00:00Z",
    createdBy: "owner",
    updatedAt: "2025-01-16T09:00:00Z",
    aiSummary: "Договір поставки товарів для ТОВ «МагазинОпт» на умовах B2B з відтермінуванням оплати 30 днів. Термін дії: до 31.12.2025.",
    // Template-based fieldValues for unified display
    templateId: "sys-supply-contract",
    fieldValues: {
      documentNumber: "ПОК-2025-001",
      documentDate: "2025-01-15",
      supplierName: "ФОП Кравченко О.П.",
      supplierCode: "4455667788",
      buyerName: "ТОВ «МагазинОпт»",
      buyerCode: "33334444",
      subject: "Поставка товарів на умовах B2B",
      deliveryTerms: "Відтермінування оплати 30 днів",
      validTo: "2025-12-31",
    },
    aiRisks: [
      {
        id: "r-deal-003-1",
        category: "financial",
        title: "Відтермінування 30 днів — ризик касового розриву",
        description: "При поставках з відтермінуванням контролюйте дебіторську заборгованість.",
        severity: "medium",
        sourceSection: "п. 4.3 «Оплата»",
        suggestion: {
          text: "Рекомендую встановити ліміт дебіторської заборгованості для контрагента та автоматичні нагадування про оплату.",
          targetSection: "Умови оплати",
          insertPosition: "append",
          confidence: 82,
        },
      },
    ],
  },
  // Рахунок-фактура (вихідний, відвантаження з відтермінуванням)
  {
    id: "doc-deal-004",
    ...DEALER_CABINET,
    number: "СФ-2025-0023",
    type: "invoice",
    category: "primary",
    title: "Рахунок-фактура на відвантаження",
    date: getDateInPast(15),
    dueDate: getDateFromNow(15),
    amount: 125000,
    currency: "UAH",
    contractor: { id: "c-deal-2", name: "ТОВ «МагазинОпт»", code: "33334444" },
    status: "sent",
    retentionPeriod: 3,
    createdAt: getDateInPast(15) + "T11:00:00Z",
    createdBy: "owner",
    updatedAt: getDateInPast(15) + "T11:00:00Z",
    aiSummary: "Рахунок-фактура на відвантаження товару для ТОВ «МагазинОпт» на суму 125 000 ₴. Відтермінування оплати 30 днів.",
    aiRisks: [
      {
        id: "r-deal-004-1",
        category: "financial",
        title: "Відтермінування платежу",
        description: "Відтермінування 30 днів — враховується в ліміт при відвантаженні",
        severity: "medium",
        sourceSection: "Умови оплати",
        suggestion: {
          text: "Дохід 125 000 грн зараховано в ліміт ФОП при відвантаженні. Контролюйте надходження коштів до дедлайну.",
          targetSection: "Умови оплати",
          insertPosition: "append",
          confidence: 88,
        },
      },
    ],
  },
  // Акт звірки взаєморозрахунків
  {
    id: "doc-deal-005",
    ...DEALER_CABINET,
    number: "ЗВІР-2025-001",
    type: "act",
    category: "primary",
    title: "Акт звірки з ТОВ «ВиробникПлюс» за Q1",
    date: getDateInPast(5),
    currency: "UAH",
    contractor: { id: "c-deal-1", name: "ТОВ «ВиробникПлюс»", code: "11112222" },
    status: "pending-sign",
    retentionPeriod: 3,
    createdAt: getDateInPast(5) + "T09:00:00Z",
    createdBy: "contractor",
    updatedAt: getDateInPast(5) + "T09:00:00Z",
    aiSummary: "Акт звірки взаєморозрахунків з ТОВ «ВиробникПлюс» за I квартал 2025. Сальдо 45 000 ₴ на користь постачальника. Очікує підпису.",
    // Template-based fieldValues for unified display
    templateId: "sys-reconciliation-act",
    fieldValues: {
      documentNumber: "ЗВІР-2025-001",
      documentDate: getDateInPast(5),
      party1Name: "ФОП Кравченко О.П.",
      party1Code: "4455667788",
      party2Name: "ТОВ «ВиробникПлюс»",
      party2Code: "11112222",
      periodStart: "2025-01-01",
      periodEnd: "2025-03-31",
      balance: "45000",
      balanceInFavor: "party2",
    },
    aiRisks: [
      {
        id: "r-deal-005-1",
        category: "legal",
        title: "Акт звірки очікує підпису",
        description: "Сальдо 45 000 грн на користь постачальника потребує підтвердження обома сторонами.",
        severity: "medium",
        sourceSection: "Підсумок",
        suggestion: {
          text: "Звірте сальдо з вашим обліком. Якщо сума коректна — підпишіть акт. При розбіжностях надішліть контрагенту коригування.",
          targetSection: "Сальдо",
          insertPosition: "append",
          confidence: 85,
        },
      },
    ],
  },
  // Договір оренди складу
  {
    id: "doc-deal-006",
    ...DEALER_CABINET,
    number: "ОРЕНДА-СКЛАД-2025",
    type: "rental-agreement",
    category: "contract",
    title: "Договір оренди складського приміщення",
    date: "2025-01-01",
    dueDate: "2025-12-31",
    amount: 18000,
    currency: "UAH",
    contractor: { id: "c-deal-3", name: "ФОП Романенко С.В.", code: "5566778899" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-01-01T08:00:00Z",
    createdBy: "contractor",
    updatedAt: "2025-01-02T10:00:00Z",
    aiSummary: "Договір оренди складського приміщення за 18 000 ₴/міс. Орендодавець — ФОП Романенко С.В. Термін дії: до 31.12.2025.",
    aiRisks: [
      {
        id: "r-deal-006-1",
        category: "deadline",
        title: "Перевірте відповідність площі",
        description: "Орендована площа складу має відповідати реальним потребам бізнесу.",
        severity: "low",
        sourceSection: "п. 1.1 «Предмет договору»",
        suggestion: {
          text: "Проаналізуйте завантаженість складу. Якщо використовується менше 70% — розгляньте зменшення площі при пролонгації.",
          targetSection: "Предмет договору",
          insertPosition: "append",
          confidence: 72,
        },
      },
    ],
  },
  // Видаткова накладна (вихідна)
  {
    id: "doc-deal-007",
    ...DEALER_CABINET,
    number: "ВН-2025-0078",
    type: "invoice",
    category: "primary",
    title: "Видаткова накладна на відвантаження",
    date: getDateInPast(1),
    amount: 68500,
    currency: "UAH",
    contractor: { id: "c-deal-4", name: "ФОП Козак І.М.", code: "7788990011" },
    status: "signed",
    retentionPeriod: 3,
    createdAt: getDateInPast(1) + "T15:00:00Z",
    createdBy: "owner",
    updatedAt: getDateInPast(1) + "T16:00:00Z",
    aiSummary: "Видаткова накладна на відвантаження товару для ФОП Козак І.М. на суму 68 500 ₴. Підписано обома сторонами.",
    // Template-based fieldValues for unified display
    templateId: "sys-waybill-standard",
    fieldValues: {
      documentNumber: "ВН-2025-0078",
      documentDate: getDateInPast(1),
      supplierName: "ФОП Кравченко О.П.",
      supplierCode: "4455667788",
      buyerName: "ФОП Козак І.М.",
      buyerCode: "7788990011",
      total: "68500",
    },
    aiRisks: [
      {
        id: "r-deal-007-1",
        category: "financial",
        title: "Відвантаження завершено",
        description: "Товар відвантажено на 68 500 грн. Перевірте надходження оплати.",
        severity: "low",
        sourceSection: "Облік",
        suggestion: {
          text: "Контролюйте оплату за відвантажений товар. Термін очікування залежить від умов договору з контрагентом.",
          targetSection: "Розрахунки",
          insertPosition: "append",
          confidence: 75,
        },
      },
    ],
  },
  // Критичний ліміт - документ що показує проблему
  {
    id: "doc-deal-008",
    ...DEALER_CABINET,
    number: "УВАГА-ЛІМІТ",
    type: "other",
    category: "internal",
    title: "⚠️ Попередження: Наближення до ліміту ФОП 2 групи",
    date: getDateFromNow(0),
    currency: "UAH",
    status: "draft",
    retentionPeriod: 1,
    createdAt: getDateFromNow(0) + "T08:00:00Z",
    createdBy: "system",
    updatedAt: getDateFromNow(0) + "T08:00:00Z",
    aiSummary: "Критичне попередження: поточний дохід 5 500 000 ₴ (98% ліміту ФОП 2 групи). При поточній динаміці ліміт буде перевищено через 2-3 тижні.",
    aiRisks: [
      {
        id: "r1",
        category: "compliance",
        title: "Критичний ліміт",
        description: "Критичне наближення до ліміту 2 групи ФОП (5 500 000 з 5 587 800 грн)",
        severity: "high",
        sourceSection: "System",
        suggestion: {
          text: "Рекомендую обмежити прийом нових замовлень або перейти на 3 групу ФОП з 01.01.2026 для уникнення штрафних санкцій за перевищення ліміту.",
          targetSection: "Рекомендації",
          insertPosition: "append",
          confidence: 96,
        },
      },
    ],
  },
];

// ============================================
// INCOME RECORDS
// ============================================

export const dealerIncomeRecords: IncomeBookRecord[] = [
  {
    id: "inc-deal-001",
    date: getDateInPast(25),
    description: "Продаж товару — ТОВ «МагазинОпт»",
    contractor: "ТОВ «МагазинОпт»",
    contractorCode: "33334444",
    amount: 98000,
    inIncomeBook: 98000,
    paymentType: "bank",
    source: "privat24",
    status: "income",
    txnId: "TXN-DEAL-001",
  },
  {
    id: "inc-deal-002",
    date: getDateInPast(20),
    description: "Продаж товару — ФОП Козак І.М.",
    contractor: "ФОП Козак І.М.",
    contractorCode: "7788990011",
    amount: 45000,
    inIncomeBook: 45000,
    paymentType: "bank",
    source: "monobank",
    status: "income",
    txnId: "TXN-DEAL-002",
  },
  {
    id: "inc-deal-003",
    date: getDateInPast(12),
    description: "Продаж товару — роздріб (каса)",
    contractor: "Фізична особа",
    amount: 12500,
    inIncomeBook: 12500,
    paymentType: "cash",
    source: "prro",
    status: "income",
    txnId: "PRRO-DEAL-001",
  },
  {
    id: "inc-deal-004",
    date: getDateInPast(5),
    description: "Продаж товару — ТОВ «МагазинОпт» (партія 42)",
    contractor: "ТОВ «МагазинОпт»",
    contractorCode: "33334444",
    amount: 125000,
    inIncomeBook: 125000,
    paymentType: "bank",
    source: "privat24",
    status: "income",
    txnId: "TXN-DEAL-003",
    documentFlowId: "doc-deal-004",
  },
  {
    id: "inc-deal-005",
    date: getDateInPast(1),
    description: "ФОП Козак — відвантаження",
    contractor: "ФОП Козак І.М.",
    contractorCode: "7788990011",
    amount: 68500,
    inIncomeBook: 68500,
    paymentType: "bank",
    source: "monobank",
    status: "income",
    txnId: "TXN-DEAL-004",
    documentFlowId: "doc-deal-007",
  },
];

// ============================================
// CONTRACTORS
// ============================================

export const dealerContractors: Contractor[] = [
  {
    id: "c-deal-1",
    name: "ТОВ «ВиробникПлюс»",
    code: "11112222",
    email: "sales@vyrobnyk.ua",
    type: "legal",
    role: "supplier",
    status: "active",
    balance: -45000,
    reliabilityScore: 92,
    activeContractsCount: 1,
    tags: ["Постачальник", "Дилер"],
    paymentTermsDays: 30,
    creditLimit: 200000,
    creditUsed: 45000,
  },
  {
    id: "c-deal-2",
    name: "ТОВ «МагазинОпт»",
    code: "33334444",
    type: "legal",
    role: "buyer",
    status: "active",
    balance: 125000,
    reliabilityScore: 75,
    activeContractsCount: 1,
    tags: ["B2B"],
    paymentTermsDays: 30,
  },
  {
    id: "c-deal-3",
    name: "ФОП Романенко С.В.",
    code: "5566778899",
    type: "fop",
    role: "supplier",
    status: "active",
    balance: -18000,
    tags: ["Оренда"],
  },
  {
    id: "c-deal-4",
    name: "ФОП Козак І.М.",
    code: "7788990011",
    type: "fop",
    role: "buyer",
    status: "active",
    balance: 0,
    reliabilityScore: 80,
    taxStatus: "Платник ЄП 2 група",
    isEdrsVerified: true,
  },
];

// ============================================
// EMPLOYEES
// ============================================

export const dealerEmployees: Employee[] = [
  {
    id: "emp-deal-001",
    cabinetId: "demo-dealer-2",
    fullName: "Бондаренко Світлана Петрівна",
    position: "Менеджер з продажу",
    contractType: "labor",
    status: "active",
    startDate: "2024-02-01",
    employmentMode: "full-time",
    fte: 1.0,
    schedule: "Пн-Пт 9:00-18:00, Сб 10:00-15:00",
    location: "office",
    contractNumber: "ТД-2024-002",
    contractDate: "2024-02-01",
    militaryStatus: "not-applicable",
    history: [
      { date: "2024-02-01", action: "Прийнято на роботу", role: "Власник" },
      { date: "2024-05-01", action: "Пройшов випробувальний термін", role: "Система" },
    ],
  },
];

// ============================================
// TAX PAYMENTS
// ============================================

export const dealerTaxPayments: TaxPayment[] = [
  {
    id: "tax-deal-001",
    cabinetId: "demo-dealer-2",
    taxType: "ep",
    taxTypeLabel: "ЄП (фікс.)",
    period: "Лютий 2025",
    year: 2025,
    month: 2,
    amountToPay: 1600,
    status: "overdue",
    statusLabel: "Прострочено",
    deadline: "2025-02-20",
    createdAt: "2025-02-10T08:00:00Z",
  },
  {
    id: "tax-deal-002",
    cabinetId: "demo-dealer-2",
    taxType: "esv",
    taxTypeLabel: "ЄСВ ФОП",
    period: "Лютий 2025",
    year: 2025,
    month: 2,
    amountToPay: 1760,
    status: "overdue",
    statusLabel: "Прострочено",
    deadline: "2025-02-20",
    createdAt: "2025-02-10T08:00:00Z",
  },
];

// ============================================
// CONTRACTOR PAYMENTS
// ============================================

export const dealerContractorPayments: ContractorPayment[] = [
  {
    id: "cp-deal-001",
    cabinetId: "demo-dealer-2",
    date: getDateFromNow(5),
    contractor: "ТОВ «ВиробникПлюс»",
    contractorId: "c-deal-1",
    purpose: "Оплата за товар (партія 45)",
    amount: 185000,
    status: "scheduled",
    statusLabel: "Заплановано",
    paymentPurposeType: "goods",
  },
  {
    id: "cp-deal-002",
    cabinetId: "demo-dealer-2",
    date: getDateFromNow(3),
    contractor: "ФОП Романенко С.В.",
    contractorId: "c-deal-3",
    purpose: "Оренда складу за лютий",
    amount: 18000,
    status: "scheduled",
    statusLabel: "Заплановано",
    paymentPurposeType: "rent",
  },
  {
    id: "cp-deal-003",
    cabinetId: "demo-dealer-2",
    date: getDateInPast(20),
    contractor: "ТОВ «ВиробникПлюс»",
    contractorId: "c-deal-1",
    purpose: "Оплата за товар (партія 43)",
    amount: 155000,
    status: "paid",
    statusLabel: "Оплачено",
    paymentPurposeType: "goods",
  },
  {
    id: "cp-deal-004",
    cabinetId: "demo-dealer-2",
    date: getDateInPast(25),
    contractor: "ФОП Романенко С.В.",
    contractorId: "c-deal-3",
    purpose: "Оренда складу за січень 2025",
    amount: 18000,
    status: "paid",
    statusLabel: "Оплачено",
    paymentPurposeType: "rent",
  },
];

// ============================================
// SALARY PAYMENTS
// ============================================

export const dealerSalaryPayments: SalaryPayment[] = [
  {
    id: "sal-deal-001",
    cabinetId: "demo-dealer-2",
    employeeId: "emp-deal-001",
    employeeName: "Бондаренко Світлана Петрівна",
    employeePosition: "Менеджер з продажу",
    salaryType: "salary",
    salaryTypeLabel: "Заробітна плата",
    period: "Січень 2025",
    amount: 17500,
    status: "paid",
    statusLabel: "Оплачено",
    scheduledDate: "2025-02-07",
    paidDate: "2025-02-07",
    source: "payroll",
    grossAmount: 25000,
    netAmount: 17500,
    pdfoAmount: 4500,
    militaryTaxAmount: 1250,
    esvAmount: 5500,
  },
];

// ============================================
// REPORTS
// ============================================

export const dealerReports: Report[] = [
  {
    id: "rep-dealer-ep-2024",
    cabinetId: "demo-dealer-2",
    type: "ep",
    typeLabel: "ЄП",
    name: "Декларація ЄП за 2024 рік",
    period: "year",
    periodLabel: "2024 рік",
    year: 2024,
    deadline: "2025-03-01",
    status: "accepted" as ReportStatus,
    statusLabel: "Прийнято",
    submittedDate: "2025-02-28",
    acceptedDate: "2025-03-01",
    dataSources: ["income-book"],
    fopGroup: 2,
    formCode: "F0103406",
    history: [],
  },
  {
    id: "rep-dealer-esv-2024",
    cabinetId: "demo-dealer-2",
    type: "esv",
    typeLabel: "ЄСВ",
    name: "Звіт з ЄСВ за 2024 рік",
    period: "year",
    periodLabel: "2024 рік",
    year: 2024,
    deadline: "2025-03-01",
    status: "accepted" as ReportStatus,
    statusLabel: "Прийнято",
    submittedDate: "2025-02-28",
    acceptedDate: "2025-03-01",
    amountToPay: 0,
    dataSources: ["income-book"],
    fopGroup: 2,
    formCode: "F0133108",
    history: [],
  },
  {
    id: "rep-dealer-1df-jan-2025-rejected",
    cabinetId: "demo-dealer-2",
    type: "1df",
    typeLabel: "Податковий розрахунок (4ДФ)",
    name: "Податковий розрахунок (4ДФ) за січень 2025",
    period: "month",
    periodLabel: "Січень 2025",
    year: 2025,
    month: 1,
    deadline: "2025-02-20",
    status: "rejected" as ReportStatus,
    statusLabel: "Відхилено",
    submittedDate: "2025-02-19",
    rejectionDetails: {
      reason: "Помилка у сумі ЄСВ: розходження з даними реєстру застрахованих осіб",
      code: "ERR-ESV-001",
      date: "2025-02-20",
      correctionDeadline: "2025-03-05",
    },
    dataSources: ["employees"],
    fopGroup: 2,
    formCode: "F0500107",
    history: [
      { date: "2025-02-19", action: "Подано" },
      { date: "2025-02-20", action: "Відхилено ДПС" },
    ],
  },
  {
    id: "rep-dealer-1df-jan-2025-corr",
    cabinetId: "demo-dealer-2",
    type: "1df",
    typeLabel: "Податковий розрахунок (4ДФ)",
    name: "Податковий розрахунок (4ДФ) за січень 2025 (виправлення)",
    period: "month",
    periodLabel: "Січень 2025",
    year: 2025,
    month: 1,
    deadline: "2025-03-05",
    status: "review" as ReportStatus,
    statusLabel: "На перевірку",
    draftProgress: 100,
    isCorrection: true,
    correctionOf: "rep-dealer-1df-jan-2025-rejected",
    correctionNumber: 1,
    correctionReason: "Виправлення помилки у сумі ЄСВ",
    originalRejectionCode: "ERR-ESV-001",
    dataSources: ["employees"],
    fopGroup: 2,
    formCode: "F0500107",
    history: [
      { date: "2025-02-25", action: "Сформовано виправлення" },
    ],
  },
  {
    id: "rep-dealer-ep-2025",
    cabinetId: "demo-dealer-2",
    type: "ep",
    typeLabel: "ЄП",
    name: "Декларація ЄП за 2025 рік",
    period: "year",
    periodLabel: "2025 рік",
    year: 2025,
    deadline: "2026-03-01",
    status: "scheduled" as ReportStatus,
    statusLabel: "Заплановано",
    dataSources: ["income-book"],
    fopGroup: 2,
    formCode: "F0103406",
    history: [],
  },
];
