/**
 * INDIVIDUAL DECLARANT CABINET (demo-individual-declarant)
 * Ткаченко Ольга Вікторівна — Фізична особа, інвестор + іноземний дохід
 * 
 * Сценарії:
 * - Інвестиції через Interactive Brokers (акції, дивіденди США)
 * - Іноземна зарплата (Польща, КУПО)
 * - Продаж авто (перший за рік — 0% ПДФО)
 * - Продаж мотоцикла (другий продаж ТЗ — 5% ПДФО + 1.5% ВЗ)
 * - Податкова знижка (навчання + медицина)
 * - Оренда квартири (ПДФО 18% + ВЗ 5%)
 * - Подарунок від родича 1-ї черги (0% ПДФО)
 * - Подарунок від не-родича (18% + 5%)
 * - Виграш у лотерею (18% + 5%)
 * - Продаж криптовалюти (18% + 5%)
 * - ЦПД / фріланс (ПДФО утримано агентом)
 * - Другий продаж нерухомості за рік (5% + 1.5%)
 */

import type { Document } from "@/config/documentFlowConfig";
import type { IncomeBookRecord } from "@/config/incomeBookConfig";
import type { TaxPayment, ContractorPayment } from "@/config/paymentsConfig";
import type { Contractor } from "@/config/settingsConfig";
import type { Report, ReportStatus } from "@/config/reportsConfig";
import { getDateFromNow, getDateInPast, getDateInMonth } from "./helpers";

// ============================================
// CABINET IDENTITY
// ============================================

const INDIVIDUAL_CABINET = {
  cabinetId: "demo-individual-declarant",
  cabinetName: "Ткаченко О.В.",
  cabinetCode: "2856734190",
};

// ============================================
// DOCUMENTS (25)
// ============================================

export const individualDocuments: Document[] = [
  // 1. Брокерський звіт IBKR
  {
    id: "doc-ind-d-001",
    ...INDIVIDUAL_CABINET,
    number: "IBKR-2024-STMT",
    type: "other",
    category: "bank",
    title: "Activity Statement Interactive Brokers за 2024 рік",
    date: "2025-01-15",
    amount: 164800,
    currency: "USD",
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-01-15T08:00:00Z",
    createdBy: "owner",
    updatedAt: "2025-01-15T08:00:00Z",
    aiSummary: "Річний звіт Interactive Brokers: реалізовано акцій Apple (+$1 200), NVIDIA (+$2 800), дивіденди Microsoft $340. Загальний інвестиційний прибуток: $4 340. Утримано withholding tax 15% з дивідендів ($51).",
    templateId: "sys-broker-statement",
    fieldValues: {
      brokerName: "Interactive Brokers LLC",
      accountId: "U1234567",
      periodFrom: "2024-01-01",
      periodTo: "2024-12-31",
      realizedPL: "+$4,000",
      dividends: "$340",
      withholdingTax: "$51",
    },
  },
  // 2. Довідка від польського роботодавця
  {
    id: "doc-ind-d-002",
    ...INDIVIDUAL_CABINET,
    number: "ZAŚ-2024-001",
    type: "certificate",
    category: "primary",
    title: "Zaświadczenie o zarobkach — IT Solutions Sp. z o.o.",
    date: "2025-01-20",
    amount: 72000,
    currency: "EUR",
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-01-20T10:00:00Z",
    createdBy: "owner",
    updatedAt: "2025-01-20T10:00:00Z",
    aiSummary: "Довідка про доходи від польського роботодавця IT Solutions Sp. z o.o. за 2024 рік. Загальний дохід: 72 000 PLN (≈ 720 000 ₴). Утримано PIT: 12% (8 640 PLN). Потрібен сертифікат резидентства для уникнення подвійного оподаткування (КУПО Україна—Польща).",
    templateId: "sys-foreign-income-certificate",
    fieldValues: {
      employerName: "IT Solutions Sp. z o.o.",
      country: "Polska",
      grossIncome: "72 000 PLN",
      taxWithheld: "8 640 PLN",
      period: "01.01.2024 — 31.12.2024",
    },
  },
  // 3. Сертифікат податкового резидентства (Polska)
  {
    id: "doc-ind-d-003",
    ...INDIVIDUAL_CABINET,
    number: "CERT-RES-2024",
    type: "certificate",
    category: "report",
    currency: "UAH",
    title: "Certyfikat Rezydencji Podatkowej (Polska) — 2024",
    date: "2024-03-15",
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2024-03-15T12:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-03-15T12:00:00Z",
    aiSummary: "Сертифікат податкового резидентства від KIS (Krajowa Informacja Skarbowa), Polska. Підтверджує, що Ткаченко О.В. є резидентом Польщі для цілей КУПО. Дійсний на 2024 рік. Необхідний для зарахування сплаченого в Польщі PIT проти ПДФО в Україні.",
  },
  // 4. Довідка про доходи — ТОВ «Діджитал Академі»
  {
    id: "doc-ind-d-004",
    ...INDIVIDUAL_CABINET,
    number: "ДОВ-2024-001",
    type: "certificate",
    category: "primary",
    title: "Довідка про доходи — ТОВ «Діджитал Академі»",
    date: "2025-01-10",
    amount: 240000,
    currency: "UAH",
    contractor: { id: "c-ind-3", name: "ТОВ «Діджитал Академі»", code: "41234567" },
    status: "signed",
    retentionPeriod: 3,
    createdAt: "2025-01-10T09:00:00Z",
    createdBy: "owner",
    updatedAt: "2025-01-10T09:00:00Z",
    aiSummary: "Довідка про доходи за 2024 рік від ТОВ «Діджитал Академі». Загальний дохід: 240 000 ₴ (20 000 ₴/міс). Утримано ПДФО 18%: 43 200 ₴, ВЗ 5%: 12 000 ₴.",
  },
  // 5. Договір купівлі-продажу авто
  {
    id: "doc-ind-d-005",
    ...INDIVIDUAL_CABINET,
    number: "КП-АВТО-2024-001",
    type: "sale-agreement",
    category: "contract",
    title: "Договір купівлі-продажу автомобіля Toyota RAV4 2020",
    date: "2024-09-20",
    amount: 580000,
    currency: "UAH",
    contractor: { id: "c-ind-6", name: "Петров Олександр Миколайович", code: "3145678901" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2024-09-20T14:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-09-20T14:00:00Z",
    aiSummary: "Продаж Toyota RAV4 2020 р.в. за 580 000 ₴. Перший продаж авто за рік — 0% ПДФО (ст. 173.2 ПКУ). Необхідно задекларувати у річній декларації як неоподатковуваний дохід. Оціночна вартість: 585 000 ₴ (відхилення < 25%, ризику немає).",
    aiRisks: [
      {
        id: "r-ind-005-1",
        category: "financial",
        title: "Перевірте кількість продажів авто за рік",
        description: "Перший продаж авто/мото за рік — 0% ПДФО. Другий та наступні — 5% ПДФО + 1.5% ВЗ.",
        severity: "low",
        sourceSection: "ст. 173.2 ПКУ",
      },
    ],
  },
  // 6. Техпаспорт авто
  {
    id: "doc-ind-d-006",
    ...INDIVIDUAL_CABINET,
    number: "ТП-АВТО-2024",
    type: "other",
    category: "internal",
    currency: "UAH",
    title: "Свідоцтво про реєстрацію ТЗ — Toyota RAV4 (АА 1234 ВВ)",
    date: "2020-05-15",
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2024-09-20T14:30:00Z",
    createdBy: "owner",
    updatedAt: "2024-09-20T14:30:00Z",
    aiSummary: "Свідоцтво про реєстрацію транспортного засобу Toyota RAV4, 2020 р.в., реєстр. номер АА 1234 ВВ. Об'єм двигуна 2.0 л. Потрібен для підтвердження продажу.",
  },
  // 7. Квитанція за навчання — 1 семестр
  {
    id: "doc-ind-d-007",
    ...INDIVIDUAL_CABINET,
    number: "КВТ-НАВ-2024-01",
    type: "receipt",
    category: "primary",
    title: "Квитанція за навчання — КНУ ім. Шевченка (1 семестр)",
    date: "2024-02-05",
    amount: 32000,
    currency: "UAH",
    contractor: { id: "c-ind-5", name: "КНУ ім. Тараса Шевченка", code: "02070987" },
    status: "confirmed",
    retentionPeriod: 5,
    createdAt: "2024-02-05T11:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-02-05T11:00:00Z",
    aiSummary: "Оплата за навчання (магістратура, юридичний факультет) за 1 семестр 2024 року. Сума: 32 000 ₴. Підлягає податковій знижці (ст. 166.3.3 ПКУ) у межах ліміту.",
  },
  // 8. Квитанція за навчання — 2 семестр
  {
    id: "doc-ind-d-008",
    ...INDIVIDUAL_CABINET,
    number: "КВТ-НАВ-2024-02",
    type: "receipt",
    category: "primary",
    title: "Квитанція за навчання — КНУ ім. Шевченка (2 семестр)",
    date: "2024-09-02",
    amount: 34000,
    currency: "UAH",
    contractor: { id: "c-ind-5", name: "КНУ ім. Тараса Шевченка", code: "02070987" },
    status: "confirmed",
    retentionPeriod: 5,
    createdAt: "2024-09-02T10:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-09-02T10:00:00Z",
    aiSummary: "Оплата за навчання (магістратура, юридичний факультет) за 2 семестр 2024 року. Сума: 34 000 ₴. Підлягає податковій знижці.",
  },
  // 9. Квитанція за медичну реабілітацію
  {
    id: "doc-ind-d-009",
    ...INDIVIDUAL_CABINET,
    number: "КВТ-МЕД-2024-01",
    type: "receipt",
    category: "primary",
    title: "Квитанція за реабілітацію — МЦ «Добробут»",
    date: "2024-07-15",
    amount: 18500,
    currency: "UAH",
    contractor: { id: "c-ind-4", name: "МЦ «Добробут»", code: "38745612" },
    status: "confirmed",
    retentionPeriod: 5,
    createdAt: "2024-07-15T16:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-07-15T16:00:00Z",
    aiSummary: "Оплата за медичну реабілітацію (курс відновлювальної терапії). Сума: 18 500 ₴. Може підлягати податковій знижці за пп. 166.3.4 ПКУ (витрати на лікування), але лише якщо заклад має відповідну ліцензію.",
  },
  // 10. Договір оренди квартири
  {
    id: "doc-ind-d-010",
    ...INDIVIDUAL_CABINET,
    number: "ОР-2024-001",
    type: "rental-agreement",
    category: "contract",
    title: "Договір оренди квартири — вул. Саксаганського, 42",
    date: "2024-01-01",
    dueDate: "2024-12-31",
    amount: 180000,
    currency: "UAH",
    contractor: { id: "c-ind-7", name: "Сидорчук Ігор Петрович", code: "2987654321" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2024-01-01T10:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-01-01T10:00:00Z",
    aiSummary: "Договір оренди квартири (3-кімнатна, 78 м², вул. Саксаганського 42, м. Київ). Орендна плата: 15 000 ₴/міс. Орендар: Сидорчук І.П. ПДФО 18% + ВЗ 5% сплачується орендодавцем (Ткаченко О.В.) самостійно.",
  },
  // 11. Банківська виписка Monobank
  {
    id: "doc-ind-d-011",
    ...INDIVIDUAL_CABINET,
    number: "ВИП-MONO-2024",
    type: "bank-statement",
    category: "bank",
    currency: "UAH",
    title: "Виписка Monobank за 2024 рік",
    date: "2025-01-05",
    status: "signed",
    retentionPeriod: 3,
    createdAt: "2025-01-05T08:00:00Z",
    createdBy: "system",
    updatedAt: "2025-01-05T08:00:00Z",
    aiSummary: "Річна виписка Monobank. Вхідні: 420 000 ₴ (зарплата, орендні платежі). Вихідні: 385 000 ₴. Синхронізовано автоматично.",
  },
  // 12. Банківська виписка WISE (валюта)
  {
    id: "doc-ind-d-012",
    ...INDIVIDUAL_CABINET,
    number: "ВИП-WISE-2024",
    type: "bank-statement",
    category: "bank",
    currency: "USD",
    title: "Виписка WISE (Multi-Currency) за 2024 рік",
    date: "2025-01-05",
    status: "signed",
    retentionPeriod: 3,
    createdAt: "2025-01-05T09:00:00Z",
    createdBy: "system",
    updatedAt: "2025-01-05T09:00:00Z",
    aiSummary: "Річна виписка WISE. Рахунки: USD ($12 400), PLN (72 000 PLN), EUR (€450). Конвертації валют: 3 операції. Зарахування від IT Solutions Sp. z o.o.: 72 000 PLN.",
  },
  // 13. Декларація 2024 (чернетка)
  {
    id: "doc-ind-d-013",
    ...INDIVIDUAL_CABINET,
    number: "ДЕКЛ-2024-DRAFT",
    type: "other",
    category: "report",
    currency: "UAH",
    title: "Декларація про майновий стан і доходи за 2024 рік (чернетка)",
    date: getDateInPast(5),
    status: "draft",
    retentionPeriod: 5,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    createdBy: "system",
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    aiSummary: "Чернетка декларації за 2024 рік. Включає: інвестиційний дохід (IBKR), іноземну зарплату (Польща), оренду, продаж авто. Розрахований ПДФО: 67 400 ₴. Податкова знижка: до 12 600 ₴ повернення. Дедлайн: 01.05.2025.",
  },
  // 14. Декларація 2023 (подана)
  {
    id: "doc-ind-d-014",
    ...INDIVIDUAL_CABINET,
    number: "ДЕКЛ-2023",
    type: "other",
    category: "report",
    currency: "UAH",
    title: "Декларація про майновий стан і доходи за 2023 рік",
    date: "2024-04-15",
    status: "confirmed",
    retentionPeriod: 5,
    createdAt: "2024-04-10T09:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-04-15T11:30:00Z",
    aiSummary: "Подана декларація за 2023 рік. Загальний дохід: 650 000 ₴. Сплачено ПДФО: 48 200 ₴. Прийнято ДПС 22.04.2024.",
  },
  // 15. Свідоцтво про спадщину — земельна ділянка
  {
    id: "doc-ind-d-015",
    ...INDIVIDUAL_CABINET,
    number: "СПАДЩ-2024-001",
    type: "other",
    category: "internal",
    title: "Свідоцтво про право на спадщину — земельна ділянка",
    date: "2024-06-10",
    amount: 120000,
    currency: "UAH",
    status: "signed",
    retentionPeriod: 10,
    createdAt: "2024-06-10T14:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-06-10T14:00:00Z",
    aiSummary: "Свідоцтво про спадщину від бабусі (1 черга спадкоємців). Земельна ділянка 0.15 га, Київська обл. Спадщина від родича 1-ї черги — 0% ПДФО (ст. 174.2.1 ПКУ). Необхідно задекларувати.",
  },

  // ---- НЕРУХОМІСТЬ: Успадкована квартира, часткова частка 1/2 (TC-07, TC-08) ----

  // 16. Свідоцтво про спадщину на квартиру (1/2 частка)
  {
    id: "doc-ind-d-016",
    ...INDIVIDUAL_CABINET,
    number: "СПАДЩ-2021-КВ",
    type: "other",
    category: "internal",
    title: "Свідоцтво про право на спадщину — 1/2 квартири (від бабусі)",
    date: "2022-03-10",
    amount: 480000,
    currency: "UAH",
    status: "signed",
    retentionPeriod: 10,
    createdAt: "2022-03-10T11:00:00Z",
    createdBy: "owner",
    updatedAt: "2022-03-10T11:00:00Z",
    aiSummary: "Свідоцтво про право на спадщину за законом. Спадкодавець: Ткаченко Галина Петрівна (бабуся, 1 черга спадкоємців). Об'єкт: 1/2 частка квартири за адресою м. Київ, вул. Лесі Українки, 28, кв. 15 (загальна площа 64 м²). Дата смерті спадкодавця: 15.11.2021. Дата державної реєстрації права власності: 10.03.2022. Для обчислення строку володіння застосовується дата смерті (15.11.2021) як більш рання (ст. 1220 ЦКУ). Оціночна вартість 1/2 частки: 480 000 ₴. Спадщина від родича 1-ї черги — 0% ПДФО (ст. 174.2.1 ПКУ).",
    aiRisks: [
      {
        id: "r-ind-016-1",
        category: "legal",
        title: "Дата набуття для спадщини: дата смерті vs дата реєстрації",
        description: "Для успадкованого майна дата набуття визначається як більш рання з: дати смерті спадкодавця (15.11.2021, ст. 1220 ЦКУ) або дати державної реєстрації (10.03.2022). Строк володіння обчислюється від 15.11.2021.",
        severity: "medium",
        sourceSection: "ст. 1220 ЦКУ, ст. 172.1 ПКУ",
      },
      {
        id: "r-ind-016-2",
        category: "financial",
        title: "Часткова частка 1/2 — база оподаткування пропорційна",
        description: "Продаж 1/2 частки квартири. База оподаткування та пільги розраховуються пропорційно до частки. 1/2 квартири = 1 об'єкт нерухомості для цілей підрахунку кількості продажів (ст. 172.1 ПКУ).",
        severity: "low",
        sourceSection: "ст. 172.1 ПКУ",
      },
    ],
    fieldValues: {
      deceasedName: "Ткаченко Галина Петрівна",
      relationship: "бабуся (1 черга спадкоємців)",
      deathDate: "2021-11-15",
      registrationDate: "2022-03-10",
      propertyType: "квартира",
      propertyAddress: "м. Київ, вул. Лесі Українки, 28, кв. 15",
      share: "1/2",
      totalArea: "64 м²",
      estimatedValue: "480 000 ₴",
    },
  },

  // 17. Витяг з реєстру нерухомості (підтвердження 1/2 частки)
  {
    id: "doc-ind-d-017",
    ...INDIVIDUAL_CABINET,
    number: "ВИТ-РЕЄСТР-2024-001",
    type: "other",
    category: "internal",
    title: "Витяг з Державного реєстру речових прав — 1/2 кв. Лесі Українки, 28",
    date: "2024-10-01",
    currency: "UAH",
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2024-10-01T09:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-10-01T09:00:00Z",
    aiSummary: "Витяг з Державного реєстру речових прав на нерухоме майно. Власник: Ткаченко Ольга Вікторівна, частка: 1/2. Об'єкт: квартира, м. Київ, вул. Лесі Українки, 28, кв. 15. Підстава набуття: свідоцтво про спадщину від 10.03.2022. Обтяження: відсутні.",
    aiRisks: [
      {
        id: "r-ind-017-1",
        category: "legal",
        title: "TC-07: Без цього документа — blocking error",
        description: "Витяг з реєстру нерухомості є обов'язковим для підтвердження права власності та частки. Без нього система не допускає фінального висновку про оподаткування продажу нерухомості (blocking error: відсутнє підтвердження частки власності).",
        severity: "high",
        sourceSection: "ст. 172 ПКУ, Validation Matrix",
      },
    ],
    fieldValues: {
      ownerName: "Ткаченко Ольга Вікторівна",
      share: "1/2",
      propertyAddress: "м. Київ, вул. Лесі Українки, 28, кв. 15",
      registrationBasis: "Свідоцтво про спадщину від 10.03.2022",
      encumbrances: "відсутні",
    },
  },

  // 18. Нотаріальний договір купівлі-продажу 1/2 квартири
  {
    id: "doc-ind-d-018",
    ...INDIVIDUAL_CABINET,
    number: "КП-КВ-2024-001",
    type: "sale-agreement",
    category: "contract",
    title: "Договір купівлі-продажу 1/2 частки квартири — вул. Лесі Українки, 28",
    date: "2024-11-05",
    amount: 520000,
    currency: "UAH",
    contractor: { id: "c-ind-8", name: "Мельник Андрій Сергійович", code: "2934567890" },
    status: "signed",
    retentionPeriod: 10,
    createdAt: "2024-11-05T15:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-11-05T15:00:00Z",
    aiSummary: "Нотаріальний договір купівлі-продажу 1/2 частки квартири за адресою м. Київ, вул. Лесі Українки, 28, кв. 15. Продавець: Ткаченко О.В. Покупець: Мельник А.С. Ціна: 520 000 ₴. Нотаріус: Бондаренко Л.М. Майно успадковане, дата набуття: 15.11.2021 (дата смерті спадкодавця). Строк володіння: > 3 років. Перший продаж нерухомості за 2024 рік → 0% ПДФО (ст. 172.1 ПКУ). Нотаріус перевірив кількість продажів за рік та підтвердив звільнення від оподаткування.",
    aiRisks: [
      {
        id: "r-ind-018-1",
        category: "financial",
        title: "Перший продаж нерухомості за рік — 0% ПДФО",
        description: "Це перший продаж об'єкта нерухомості у 2024 році. Строк володіння > 3 років (з 15.11.2021). Відповідно до ст. 172.1 ПКУ — дохід не оподатковується ПДФО. При другому продажі нерухомості у тому ж році — ставка 5% ПДФО + 1.5% ВЗ.",
        severity: "low",
        sourceSection: "ст. 172.1 ПКУ",
      },
      {
        id: "r-ind-018-2",
        category: "legal",
        title: "TC-07: Blocking error при відсутності дати набуття",
        description: "Система не допускає фінального висновку без інформації про дату набуття, тип об'єкта та кількість продажів у звітному році. Якщо дата набуття відсутня — формується blocking error, що блокує формування декларації.",
        severity: "high",
        sourceSection: "ст. 172 ПКУ, Розділ 12 ТЗ",
      },
      {
        id: "r-ind-018-3",
        category: "legal",
        title: "TC-08: Дата набуття для спадщини — дата смерті (15.11.2021)",
        description: "Для успадкованого майна строк володіння обчислюється від дати смерті спадкодавця (15.11.2021), а не від дати реєстрації (10.03.2022). Це дає > 3 років володіння на момент продажу (05.11.2024), що є підставою для звільнення від ПДФО.",
        severity: "medium",
        sourceSection: "ст. 1220 ЦКУ, ст. 172.1 ПКУ",
      },
    ],
    fieldValues: {
      propertyType: "квартира (1/2 частка)",
      propertyAddress: "м. Київ, вул. Лесі Українки, 28, кв. 15",
      share: "1/2",
      totalArea: "64 м²",
      salePrice: "520 000 ₴",
      buyerName: "Мельник Андрій Сергійович",
      buyerCode: "2934567890",
      notaryName: "Бондаренко Лариса Миколаївна",
      acquisitionDate: "2021-11-15",
      acquisitionBasis: "Спадщина (свідоцтво від 10.03.2022)",
      ownershipYears: "3 роки 0 місяців",
      salesCountThisYear: "1 (перший)",
      taxRate: "0%",
      taxAmount: "0 ₴",
    },
  },

  // ---- НОВІ ТИПИ ДОХОДІВ (1.17-1.22 + 3.7) ----

  // 19. Дарча від матері (1.17 — подарунок від родича 1-ї черги, 0% ПДФО)
  {
    id: "doc-ind-d-019",
    ...INDIVIDUAL_CABINET,
    number: "ДАРЧ-2024-001",
    type: "other",
    category: "internal",
    title: "Нотаріальне посвідчення дарування — грошовий подарунок від матері",
    date: "2024-03-08",
    amount: 50000,
    currency: "UAH",
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2024-03-08T12:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-03-08T12:00:00Z",
    aiSummary: "Нотаріально посвідчений договір дарування. Дарувальник: Ткаченко Віра Степанівна (мати — 1 черга спадкоємців/родичів). Обдаровуваний: Ткаченко О.В. Сума: 50 000 ₴. Подарунок від родича 1-ї черги — 0% ПДФО (ст. 174.2.1 ПКУ). Необхідно задекларувати як неоподатковуваний дохід.",
    fieldValues: {
      donorName: "Ткаченко Віра Степанівна",
      relationship: "мати (1 черга)",
      amount: "50 000 ₴",
      taxRate: "0%",
      legalBasis: "ст. 174.2.1 ПКУ",
    },
  },

  // 20. Переказ-подарунок від друга (1.18 — подарунок від не-родича, 18% + 5%)
  {
    id: "doc-ind-d-020",
    ...INDIVIDUAL_CABINET,
    number: "ДАРЧ-2024-002",
    type: "other",
    category: "primary",
    title: "Підтвердження грошового переказу — подарунок від Коваленко І.М.",
    date: "2024-05-20",
    amount: 30000,
    currency: "UAH",
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2024-05-20T15:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-05-20T15:00:00Z",
    aiSummary: "Грошовий подарунок від Коваленко Ірини Миколаївни (подруга, не є родичем 1-ї або 2-ї черги). Сума: 30 000 ₴. Подарунок від не-родича оподатковується ПДФО 18% (5 400 ₴) + ВЗ 5% (1 500 ₴). Загальний податок: 6 900 ₴.",
    contractor: { id: "c-ind-9", name: "Коваленко Ірина Миколаївна", code: "2876543210" },
    fieldValues: {
      donorName: "Коваленко Ірина Миколаївна",
      relationship: "подруга (не родич)",
      amount: "30 000 ₴",
      taxRate: "18% ПДФО + 5% ВЗ",
      pdfo: "5 400 ₴",
      vz: "1 500 ₴",
    },
  },

  // 21. Довідка про виграш у лотерею (1.19 — 18% + 5%)
  {
    id: "doc-ind-d-021",
    ...INDIVIDUAL_CABINET,
    number: "ВИГ-ЛОТ-2024-001",
    type: "certificate",
    category: "primary",
    title: "Довідка про виплату виграшу — МСЛ «Мегалот»",
    date: "2024-08-10",
    amount: 15000,
    currency: "UAH",
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2024-08-10T11:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-08-10T11:00:00Z",
    aiSummary: "Довідка про виплату виграшу в державну лотерею «Мегалот». Сума виграшу: 15 000 ₴. Перевищує поріг 4 324 ₴ (50% МЗП 2026). Оператор: МСЛ (Державні лотереї). ПДФО 18% (2 700 ₴) + ВЗ 5% (750 ₴). Оператор лотереї є податковим агентом, але за цією сумою ПДФО не утримується автоматично — декларує платник.",
    contractor: { id: "c-ind-10", name: "ТОВ «МСЛ» (Державні лотереї)", code: "33aborcode" },
    fieldValues: {
      operatorName: "ТОВ «МСЛ» (Державні лотереї)",
      winningAmount: "15 000 ₴",
      threshold: "4 324 ₴ (50% МЗП)",
      taxRate: "18% ПДФО + 5% ВЗ",
      legalBasis: "ст. 170.6 ПКУ",
    },
  },

  // 22. Звіт Binance за 2024 (1.20 — криптовалюта, 18% + 5%)
  {
    id: "doc-ind-d-022",
    ...INDIVIDUAL_CABINET,
    number: "КРИПТО-BIN-2024",
    type: "other",
    category: "bank",
    title: "Звіт Binance — продаж BTC за 2024 рік",
    date: "2025-01-10",
    amount: 85000,
    currency: "UAH",
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2025-01-10T10:00:00Z",
    createdBy: "owner",
    updatedAt: "2025-01-10T10:00:00Z",
    aiSummary: "Звіт з біржі Binance за 2024 рік. Продано 0.035 BTC за ≈ 85 000 ₴ (курс НБУ на дату операції). Купівля: 0.035 BTC за 62 000 ₴ у 2023. Прибуток: 23 000 ₴. Криптовалюта в Україні оподатковується як інший дохід: ПДФО 18% (4 140 ₴) + ВЗ 5% (1 150 ₴) від прибутку.",
    templateId: "sys-crypto-report",
    fieldValues: {
      exchangeName: "Binance",
      asset: "BTC (Bitcoin)",
      soldAmount: "0.035 BTC",
      salePrice: "85 000 ₴",
      costBasis: "62 000 ₴",
      profit: "23 000 ₴",
      taxRate: "18% ПДФО + 5% ВЗ",
    },
  },

  // 23. ЦПД з ТОВ «ВебСтудія» (1.21 — фріланс, ПДФО утримано)
  {
    id: "doc-ind-d-023",
    ...INDIVIDUAL_CABINET,
    number: "ЦПД-2024-001",
    type: "contract",
    category: "contract",
    title: "Цивільно-правовий договір — ТОВ «ВебСтудія Про»",
    date: "2024-04-01",
    dueDate: "2024-06-30",
    amount: 45000,
    currency: "UAH",
    contractor: { id: "c-ind-11", name: "ТОВ «ВебСтудія Про»", code: "43567890" },
    status: "signed",
    retentionPeriod: 3,
    createdAt: "2024-04-01T09:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-06-30T18:00:00Z",
    aiSummary: "ЦПД (цивільно-правовий договір) на розробку дизайну сайту. Замовник: ТОВ «ВебСтудія Про» (податковий агент). Сума: 45 000 ₴. ПДФО 18% (8 100 ₴) та ВЗ 5% (2 250 ₴) утримані замовником при виплаті. Чистий дохід: 34 650 ₴. Необхідно задекларувати повну суму, з вказанням утриманого податку.",
    fieldValues: {
      employerName: "ТОВ «ВебСтудія Про»",
      contractType: "ЦПД (цивільно-правовий договір)",
      grossAmount: "45 000 ₴",
      pdfoWithheld: "8 100 ₴",
      vzWithheld: "2 250 ₴",
      netAmount: "34 650 ₴",
    },
  },

  // 24. ДКП мотоцикла — другий продаж ТЗ за рік (1.22 — 5% + 1.5%)
  {
    id: "doc-ind-d-024",
    ...INDIVIDUAL_CABINET,
    number: "КП-МОТО-2024-001",
    type: "sale-agreement",
    category: "contract",
    title: "Договір купівлі-продажу мотоцикла Honda CB500F 2022",
    date: "2024-11-15",
    amount: 95000,
    currency: "UAH",
    contractor: { id: "c-ind-12", name: "Литвин Максим Олегович", code: "3056789012" },
    status: "signed",
    retentionPeriod: 5,
    createdAt: "2024-11-15T16:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-11-15T16:00:00Z",
    aiSummary: "Продаж мотоцикла Honda CB500F, 2022 р.в. за 95 000 ₴. УВАГА: це другий продаж транспортного засобу за 2024 рік (перший — Toyota RAV4 у вересні). Другий продаж ТЗ оподатковується: ПДФО 5% (4 750 ₴) + ВЗ 1.5% (1 425 ₴). Загальний податок: 6 175 ₴.",
    aiRisks: [
      {
        id: "r-ind-024-1",
        category: "financial",
        title: "Другий продаж ТЗ за рік — 5% ПДФО + 1.5% ВЗ",
        description: "Це другий продаж транспортного засобу у 2024 році (перший — Toyota RAV4 20.09.2024). Відповідно до ст. 173.2 ПКУ, другий та наступні продажі оподатковуються 5% ПДФО + 1.5% ВЗ від суми продажу.",
        severity: "high",
        sourceSection: "ст. 173.2 ПКУ",
      },
    ],
    fieldValues: {
      vehicleBrand: "Honda CB500F",
      vehicleYear: "2022",
      salePrice: "95 000 ₴",
      saleNumber: "2 (другий за рік)",
      taxRate: "5% ПДФО + 1.5% ВЗ",
      pdfo: "4 750 ₴",
      vz: "1 425 ₴",
    },
  },

  // 25. ДКП гаражу — другий продаж нерухомості за рік (3.7 — 5% + 1.5%)
  {
    id: "doc-ind-d-025",
    ...INDIVIDUAL_CABINET,
    number: "КП-ГАРАЖ-2024-001",
    type: "sale-agreement",
    category: "contract",
    title: "Договір купівлі-продажу гаражу — Бортничі, масив Садовий",
    date: "2024-12-10",
    amount: 180000,
    currency: "UAH",
    contractor: { id: "c-ind-13", name: "Захарченко Денис Вікторович", code: "2912345678" },
    status: "signed",
    retentionPeriod: 10,
    createdAt: "2024-12-10T14:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-12-10T14:00:00Z",
    aiSummary: "Продаж гаражу (Бортничі, масив Садовий, бокс №47). УВАГА: це другий продаж нерухомості за 2024 рік (перший — 1/2 квартири на Лесі Українки у листопаді). Другий продаж оподатковується: ПДФО 5% (9 000 ₴) + ВЗ 1.5% (2 700 ₴). Загальний податок: 11 700 ₴. Ст. 172.2 ПКУ.",
    aiRisks: [
      {
        id: "r-ind-025-1",
        category: "financial",
        title: "Другий продаж нерухомості за рік — 5% ПДФО + 1.5% ВЗ",
        description: "Це другий продаж нерухомості у 2024 році (перший — квартира 05.11.2024). Ст. 172.2 ПКУ: дохід від другого та подальших продажів нерухомості протягом року оподатковується 5% ПДФО + 1.5% ВЗ.",
        severity: "high",
        sourceSection: "ст. 172.2 ПКУ",
      },
    ],
    fieldValues: {
      propertyType: "гараж",
      propertyAddress: "м. Київ, Бортничі, масив Садовий, бокс №47",
      salePrice: "180 000 ₴",
      salesCountThisYear: "2 (другий)",
      taxRate: "5% ПДФО + 1.5% ВЗ",
      pdfo: "9 000 ₴",
      vz: "2 700 ₴",
    },
  },
  // 26. W-8BEN довідка (підтвердження WHT 15% для US-брокера)
  {
    id: "doc-ind-d-026",
    ...INDIVIDUAL_CABINET,
    number: "W8BEN-2024-001",
    type: "certificate",
    category: "internal",
    title: "Форма W-8BEN — Certificate of Foreign Status (IBKR)",
    date: "2024-01-15",
    amount: 0,
    currency: "USD",
    contractor: { id: "c-ind-14", name: "Interactive Brokers LLC", code: "IBKR" },
    status: "signed",
    retentionPeriod: 3,
    createdAt: "2024-01-15T10:00:00Z",
    createdBy: "owner",
    updatedAt: "2024-01-15T10:00:00Z",
    aiSummary: "Форма W-8BEN подана до Interactive Brokers для підтвердження статусу нерезидента США. Дозволяє застосувати знижену ставку WHT 15% (замість 30%) на дивіденди згідно з Конвенцією про уникнення подвійного оподаткування між Україною та США. Діє 3 роки до 15.01.2027.",
    aiRisks: [
      {
        id: "r-ind-026-1",
        category: "compliance",
        title: "Термін дії W-8BEN — до 15.01.2027",
        description: "Форма W-8BEN дійсна протягом 3 років. Після закінчення терміну необхідно подати нову форму, інакше WHT зросте з 15% до 30%.",
        severity: "medium",
        sourceSection: "IRS Form W-8BEN Instructions",
      },
    ],
    fieldValues: {
      formType: "W-8BEN",
      broker: "Interactive Brokers LLC",
      whtRate: "15%",
      treatyArticle: "Article 10 (Dividends) UA-US Tax Treaty",
      validUntil: "15.01.2027",
    },
  },
];

// ============================================
// INCOME RECORDS (18)
// ============================================

export const individualIncomeRecords: IncomeBookRecord[] = [
  // ============================================
  // 2025 — поточний звітний рік (декларація формується автоматично)
  // ============================================
  {
    id: "inc-ind-001",
    date: getDateInMonth(2025, 8, 15),
    description: "Продаж акцій Apple Inc. (AAPL) — реалізований прибуток",
    amount: 49440,
    inIncomeBook: 49440,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "Interactive Brokers LLC",
    contractorCode: "US1234567",
    documentFlowId: "doc-ind-d-001",
  },
  {
    id: "inc-ind-002",
    date: getDateInMonth(2025, 11, 20),
    description: "Продаж акцій NVIDIA Corp. (NVDA) — реалізований прибуток",
    amount: 115360,
    inIncomeBook: 115360,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "Interactive Brokers LLC",
    contractorCode: "US1234567",
    documentFlowId: "doc-ind-d-001",
  },
  {
    id: "inc-ind-003",
    date: getDateInMonth(2025, 6, 15),
    description: "Дивіденди Microsoft Corp. (MSFT) — після withholding tax 15%",
    amount: 11900,
    inIncomeBook: 11900,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "Interactive Brokers LLC",
    contractorCode: "US1234567",
    documentFlowId: "doc-ind-d-001",
  },
  {
    id: "inc-ind-004",
    date: getDateInMonth(2025, 12, 31),
    description: "Заробітна плата IT Solutions Sp. z o.o. (Polska) — за 2025 рік",
    amount: 720000,
    inIncomeBook: 720000,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "IT Solutions Sp. z o.o.",
    contractorCode: "PL5678901234",
    documentFlowId: "doc-ind-d-002",
  },
  {
    id: "inc-ind-005",
    date: getDateInMonth(2025, 12, 31),
    description: "Заробітна плата ТОВ «Діджитал Академі» за 2025 рік",
    amount: 240000,
    inIncomeBook: 240000,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "ТОВ «Діджитал Академі»",
    contractorCode: "41234567",
    documentFlowId: "doc-ind-d-004",
  },
  {
    id: "inc-ind-006",
    date: getDateInMonth(2025, 12, 31),
    description: "Орендна плата за квартиру (вул. Саксаганського 42) — за 2025 рік",
    amount: 180000,
    inIncomeBook: 180000,
    paymentType: "bank",
    source: "monobank",
    status: "income",
    contractor: "Сидорчук Ігор Петрович",
    contractorCode: "2987654321",
    documentFlowId: "doc-ind-d-010",
  },
  {
    id: "inc-ind-007",
    date: getDateInMonth(2025, 9, 20),
    description: "Продаж автомобіля Toyota RAV4 2020 (перший продаж за рік — 0% ПДФО)",
    amount: 580000,
    inIncomeBook: 0,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "Петров Олександр Миколайович",
    contractorCode: "3145678901",
    documentFlowId: "doc-ind-d-005",
  },
  {
    id: "inc-ind-008",
    date: getDateInMonth(2025, 6, 10),
    description: "Спадщина — земельна ділянка 0.15 га, Київська обл. (1 черга — 0% ПДФО)",
    amount: 120000,
    inIncomeBook: 0,
    paymentType: "bank",
    source: "manual",
    status: "not-income",
    contractor: "Нотаріус Бондаренко Л.М.",
    documentFlowId: "doc-ind-d-015",
  },
  {
    id: "inc-ind-009",
    date: getDateInMonth(2025, 4, 10),
    description: "Конвертація PLN → UAH через WISE (переказ на Monobank)",
    amount: 45000,
    inIncomeBook: 0,
    paymentType: "bank",
    source: "manual",
    status: "not-income",
    contractor: "WISE Europe SA",
    documentFlowId: "doc-ind-d-012",
  },
  {
    id: "inc-ind-010",
    date: getDateInMonth(2025, 10, 5),
    description: "Переказ від ПІБ невідомий — потребує класифікації",
    amount: 25000,
    inIncomeBook: 0,
    paymentType: "bank",
    source: "monobank",
    status: "needs-clarification",
    issueType: "unknown-contractor",
  },
  // TC-08: Продаж 1/2 успадкованої квартири — 0% ПДФО (ст. 172.1 ПКУ)
  {
    id: "inc-ind-011",
    date: getDateInMonth(2025, 11, 5),
    description: "Продаж 1/2 частки квартири (вул. Лесі Українки, 28) — успадкована, > 3 років, перший продаж — 0% ПДФО",
    amount: 520000,
    inIncomeBook: 0,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "Мельник Андрій Сергійович",
    contractorCode: "2934567890",
    documentFlowId: "doc-ind-d-018",
  },

  // ---- НОВІ ТИПИ ДОХОДІВ (1.17-1.22 + 3.7) — все 2025 ----

  {
    id: "inc-ind-012",
    date: getDateInMonth(2025, 3, 8),
    description: "Грошовий подарунок від матері (1 черга — 0% ПДФО, ст. 174.2.1 ПКУ)",
    amount: 50000,
    inIncomeBook: 0,
    paymentType: "bank",
    source: "monobank",
    status: "not-income",
    contractor: "Ткаченко Віра Степанівна",
    contractorCode: "2845678901",
    documentFlowId: "doc-ind-d-019",
  },
  {
    id: "inc-ind-013",
    date: getDateInMonth(2025, 5, 20),
    description: "Грошовий подарунок від Коваленко І.М. (не родич — 18% ПДФО + 5% ВЗ)",
    amount: 30000,
    inIncomeBook: 30000,
    paymentType: "bank",
    source: "monobank",
    status: "income",
    contractor: "Коваленко Ірина Миколаївна",
    contractorCode: "2876543210",
    documentFlowId: "doc-ind-d-020",
  },
  {
    id: "inc-ind-014",
    date: getDateInMonth(2025, 8, 10),
    description: "Виграш у державну лотерею «Мегалот» (перевищує поріг 4 324 ₴)",
    amount: 15000,
    inIncomeBook: 15000,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "ТОВ «МСЛ» (Державні лотереї)",
    contractorCode: "33aborcode",
    documentFlowId: "doc-ind-d-021",
  },
  {
    id: "inc-ind-015",
    date: getDateInMonth(2025, 12, 5),
    description: "Продаж 0.035 BTC через Binance — прибуток 23 000 ₴ (18% ПДФО + 5% ВЗ)",
    amount: 85000,
    inIncomeBook: 23000,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "Binance (Crypto Exchange)",
    contractorCode: "BINANCE",
    documentFlowId: "doc-ind-d-022",
  },
  {
    id: "inc-ind-016",
    date: getDateInMonth(2025, 6, 30),
    description: "Дохід за ЦПД — ТОВ «ВебСтудія Про» (ПДФО 18% + ВЗ 5% утримано)",
    amount: 45000,
    inIncomeBook: 45000,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "ТОВ «ВебСтудія Про»",
    contractorCode: "43567890",
    documentFlowId: "doc-ind-d-023",
  },
  {
    id: "inc-ind-017",
    date: getDateInMonth(2025, 11, 15),
    description: "Продаж мотоцикла Honda CB500F (другий продаж ТЗ за рік — 5% ПДФО + 1.5% ВЗ)",
    amount: 95000,
    inIncomeBook: 95000,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "Литвин Максим Олегович",
    contractorCode: "3056789012",
    documentFlowId: "doc-ind-d-024",
  },
  {
    id: "inc-ind-018",
    date: getDateInMonth(2025, 12, 10),
    description: "Продаж гаражу (другий продаж нерухомості за рік — 5% ПДФО + 1.5% ВЗ, ст. 172.2)",
    amount: 180000,
    inIncomeBook: 180000,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "Захарченко Денис Вікторович",
    contractorCode: "2912345678",
    documentFlowId: "doc-ind-d-025",
  },

  // ============================================
  // 2024 — історичні (для submitted-кейса case-2024-submitted)
  // Тільки 3 ключові операції — щоб видно було історію в Книзі доходів
  // ============================================
  {
    id: "inc-ind-2024-01",
    date: getDateInMonth(2024, 12, 31),
    description: "Заробітна плата ТОВ «Діджитал Академі» за 2024 рік (історія)",
    amount: 240000,
    inIncomeBook: 240000,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "ТОВ «Діджитал Академі»",
    contractorCode: "41234567",
    documentFlowId: "doc-ind-d-004",
  },
  {
    id: "inc-ind-2024-02",
    date: getDateInMonth(2024, 12, 31),
    description: "Орендна плата (Саксаганського 42) — за 2024 рік (історія)",
    amount: 180000,
    inIncomeBook: 180000,
    paymentType: "bank",
    source: "monobank",
    status: "income",
    contractor: "Сидорчук Ігор Петрович",
    contractorCode: "2987654321",
    documentFlowId: "doc-ind-d-010",
  },
  {
    id: "inc-ind-2024-03",
    date: getDateInMonth(2024, 8, 15),
    description: "Продаж AAPL — реалізований прибуток (історія 2024)",
    amount: 49440,
    inIncomeBook: 49440,
    paymentType: "bank",
    source: "manual",
    status: "income",
    contractor: "Interactive Brokers LLC",
    contractorCode: "US1234567",
    documentFlowId: "doc-ind-d-001",
  },
];

// ============================================
// CONTRACTORS (13)
// ============================================

export const individualContractors: Contractor[] = [
  {
    id: "c-ind-1",
    name: "Interactive Brokers LLC",
    fullName: "Interactive Brokers LLC (USA)",
    code: "US1234567",
    type: "legal",
    role: "supplier",
    email: "support@interactivebrokers.com",
    address: "One Pickwick Plaza, Greenwich, CT 06830, USA",
    status: "active",
    verificationStatus: "verified",
    lastActivityDate: "2025-01-15",
    notes: "Брокер для інвестицій у цінні папери. Рахунок U1234567.",
    tags: ["брокер", "інвестиції", "іноземний"],
  },
  {
    id: "c-ind-2",
    name: "IT Solutions Sp. z o.o.",
    fullName: "IT Solutions Spółka z ograniczoną odpowiedzialnością",
    code: "PL5678901234",
    type: "legal",
    role: "supplier",
    email: "hr@itsolutions.pl",
    address: "ul. Marszałkowska 15, 00-001 Warszawa, Polska",
    status: "active",
    verificationStatus: "verified",
    lastActivityDate: "2024-12-31",
    notes: "Роботодавець (Польща). Контракт B2B / umowa o pracę. КУПО застосовується.",
    tags: ["роботодавець", "іноземний", "Польща"],
  },
  {
    id: "c-ind-3",
    name: "ТОВ «Діджитал Академі»",
    fullName: "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ «ДІДЖИТАЛ АКАДЕМІ»",
    code: "41234567",
    type: "legal",
    role: "supplier",
    iban: "UA213223130000026007233566001",
    ibanConfirmed: true,
    email: "hr@digitalacademy.ua",
    address: "м. Київ, вул. Богдана Хмельницького, 10",
    status: "active",
    verificationStatus: "verified",
    lastActivityDate: "2024-12-31",
    notes: "Основний роботодавець в Україні. Трудовий договір.",
    tags: ["роботодавець", "Україна"],
    isEdrsVerified: true,
  },
  {
    id: "c-ind-4",
    name: "МЦ «Добробут»",
    fullName: "ТОВ «МЕДИЧНИЙ ЦЕНТР «ДОБРОБУТ»",
    code: "38745612",
    type: "legal",
    role: "supplier",
    address: "м. Київ, вул. Кирилівська, 120",
    status: "active",
    verificationStatus: "verified",
    notes: "Медичний заклад з ліцензією. Витрати на реабілітацію — податкова знижка.",
    tags: ["медицина", "податкова знижка"],
  },
  {
    id: "c-ind-5",
    name: "КНУ ім. Тараса Шевченка",
    fullName: "Київський національний університет імені Тараса Шевченка",
    code: "02070987",
    type: "legal",
    role: "supplier",
    address: "м. Київ, вул. Володимирська, 60",
    status: "active",
    verificationStatus: "verified",
    notes: "Навчальний заклад. Оплата за магістратуру — підлягає податковій знижці.",
    tags: ["навчання", "податкова знижка"],
    isEdrsVerified: true,
  },
  {
    id: "c-ind-6",
    name: "Петров Олександр Миколайович",
    code: "3145678901",
    type: "individual",
    role: "buyer",
    status: "active",
    verificationStatus: "unverified",
    lastActivityDate: "2024-09-20",
    notes: "Покупець авто Toyota RAV4.",
    tags: ["покупець", "авто"],
  },
  {
    id: "c-ind-7",
    name: "Сидорчук Ігор Петрович",
    code: "2987654321",
    type: "individual",
    role: "buyer",
    iban: "UA413052990000026007123456789",
    ibanConfirmed: true,
    phone: "+380671234567",
    status: "active",
    verificationStatus: "verified",
    lastActivityDate: "2024-12-31",
    notes: "Орендар квартири на вул. Саксаганського 42. Сплачує 15 000 ₴/міс.",
    tags: ["орендар", "оренда"],
  },
  // TC-08: Покупець 1/2 успадкованої квартири
  {
    id: "c-ind-8",
    name: "Мельник Андрій Сергійович",
    code: "2934567890",
    type: "individual",
    role: "buyer",
    phone: "+380501234567",
    status: "active",
    verificationStatus: "unverified",
    lastActivityDate: "2024-11-05",
    notes: "Покупець 1/2 частки квартири (вул. Лесі Українки, 28, кв. 15). Договір від 05.11.2024.",
    tags: ["покупець", "нерухомість"],
  },
  // ---- НОВІ КОНТРАГЕНТИ (1.17-1.22 + 3.7) ----
  {
    id: "c-ind-9",
    name: "Коваленко Ірина Миколаївна",
    code: "2876543210",
    type: "individual",
    role: "supplier",
    status: "active",
    verificationStatus: "unverified",
    lastActivityDate: "2024-05-20",
    notes: "Подруга, яка зробила грошовий подарунок 30 000 ₴. Не родич — 18% ПДФО + 5% ВЗ.",
    tags: ["подарунок", "не-родич"],
  },
  {
    id: "c-ind-10",
    name: "ТОВ «МСЛ» (Державні лотереї)",
    fullName: "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ «МСЛ»",
    code: "33absorcode",
    type: "legal",
    role: "supplier",
    address: "м. Київ, вул. Хрещатик, 22",
    status: "active",
    verificationStatus: "verified",
    notes: "Оператор державних лотерей. Виграш 15 000 ₴ (перевищує поріг 4 324 ₴).",
    tags: ["лотерея", "виграш"],
  },
  {
    id: "c-ind-11",
    name: "ТОВ «ВебСтудія Про»",
    fullName: "ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ «ВЕБСТУДІЯ ПРО»",
    code: "43567890",
    type: "legal",
    role: "supplier",
    iban: "UA213223130000026007111222333",
    ibanConfirmed: true,
    email: "info@webstudio.pro",
    address: "м. Київ, вул. Антоновича, 88",
    status: "active",
    verificationStatus: "verified",
    lastActivityDate: "2024-06-30",
    notes: "Замовник по ЦПД (дизайн сайту). Податковий агент — утримує ПДФО 18% + ВЗ 5%.",
    tags: ["замовник", "ЦПД", "фріланс"],
    isEdrsVerified: true,
  },
  {
    id: "c-ind-12",
    name: "Литвин Максим Олегович",
    code: "3056789012",
    type: "individual",
    role: "buyer",
    status: "active",
    verificationStatus: "unverified",
    lastActivityDate: "2024-11-15",
    notes: "Покупець мотоцикла Honda CB500F. Другий продаж ТЗ за рік.",
    tags: ["покупець", "мотоцикл"],
  },
  {
    id: "c-ind-13",
    name: "Захарченко Денис Вікторович",
    code: "2912345678",
    type: "individual",
    role: "buyer",
    phone: "+380631234567",
    status: "active",
    verificationStatus: "unverified",
    lastActivityDate: "2024-12-10",
    notes: "Покупець гаражу (Бортничі). Другий продаж нерухомості за рік.",
    tags: ["покупець", "нерухомість", "гараж"],
  },
];

// ============================================
// TAX PAYMENTS (17)
// ============================================

export const individualTaxPayments: TaxPayment[] = [
  {
    id: "tp-ind-001",
    cabinetId: "demo-individual-declarant",
    taxType: "pdfo",
    taxTypeLabel: "ПДФО (інвестиційний дохід)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 31820,
    status: "not-created",
    statusLabel: "Не створено",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11010100",
  },
  {
    id: "tp-ind-002",
    cabinetId: "demo-individual-declarant",
    taxType: "military",
    taxTypeLabel: "ВЗ (інвестиційний дохід)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 8840,
    status: "not-created",
    statusLabel: "Не створено",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11011000",
  },
  {
    id: "tp-ind-003",
    cabinetId: "demo-individual-declarant",
    taxType: "pdfo",
    taxTypeLabel: "ПДФО (оренда квартири)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 32400,
    status: "paid",
    statusLabel: "Сплачено",
    deadline: "2025-04-30",
    paidDate: "2025-02-15",
    paidAmount: 32400,
    createdAt: getDateInPast(30),
    budgetCode: "11010100",
    bankProvider: "monobank",
    bankLabel: "Monobank",
  },
  {
    id: "tp-ind-004",
    cabinetId: "demo-individual-declarant",
    taxType: "military",
    taxTypeLabel: "ВЗ (оренда квартири)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 9000,
    status: "paid",
    statusLabel: "Сплачено",
    deadline: "2025-04-30",
    paidDate: "2025-02-15",
    paidAmount: 9000,
    createdAt: getDateInPast(30),
    budgetCode: "11011000",
    bankProvider: "monobank",
    bankLabel: "Monobank",
  },
  {
    id: "tp-ind-005",
    cabinetId: "demo-individual-declarant",
    taxType: "pdfo",
    taxTypeLabel: "ПДФО (іноземна зарплата, після КУПО)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 43200,
    status: "not-created",
    statusLabel: "Не створено",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11010100",
  },
  {
    id: "tp-ind-006",
    cabinetId: "demo-individual-declarant",
    taxType: "other",
    taxTypeLabel: "Податок на нерухомість",
    period: "2024 рік",
    year: 2024,
    amountToPay: 3300,
    status: "paid",
    statusLabel: "Сплачено",
    deadline: "2024-07-01",
    paidDate: "2024-06-25",
    paidAmount: 3300,
    createdAt: "2024-06-01",
    budgetCode: "18010100",
    bankProvider: "monobank",
    bankLabel: "Monobank",
  },
  // TC-08: Продаж 1/2 квартири — 0% ПДФО (перший продаж нерухомості, > 3 років)
  {
    id: "tp-ind-007",
    cabinetId: "demo-individual-declarant",
    taxType: "pdfo",
    taxTypeLabel: "ПДФО (продаж 1/2 квартири — пільга ст. 172.1)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 0,
    status: "cancelled",
    statusLabel: "Не потрібен",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11010100",
    // Перший продаж нерухомості за 2024 рік. Строк володіння > 3 років. 0% ПДФО (ст. 172.1 ПКУ).
  },
  // ---- НОВІ ПОДАТКОВІ ПЛАТЕЖІ (1.18, 1.19, 1.20, 1.22, 3.7) ----
  // 1.18: Подарунок від не-родича — ПДФО 18%
  {
    id: "tp-ind-008",
    cabinetId: "demo-individual-declarant",
    taxType: "pdfo",
    taxTypeLabel: "ПДФО (подарунок від не-родича)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 5400,
    status: "not-created",
    statusLabel: "Не створено",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11010100",
  },
  {
    id: "tp-ind-009",
    cabinetId: "demo-individual-declarant",
    taxType: "military",
    taxTypeLabel: "ВЗ (подарунок від не-родича)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 1500,
    status: "not-created",
    statusLabel: "Не створено",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11011000",
  },
  // 1.19: Виграш у лотерею — ПДФО 18% + ВЗ 5%
  {
    id: "tp-ind-010",
    cabinetId: "demo-individual-declarant",
    taxType: "pdfo",
    taxTypeLabel: "ПДФО (виграш у лотерею)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 2700,
    status: "not-created",
    statusLabel: "Не створено",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11010100",
  },
  {
    id: "tp-ind-011",
    cabinetId: "demo-individual-declarant",
    taxType: "military",
    taxTypeLabel: "ВЗ (виграш у лотерею)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 750,
    status: "not-created",
    statusLabel: "Не створено",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11011000",
  },
  // 1.20: Криптовалюта — ПДФО 18% + ВЗ 5% від прибутку
  {
    id: "tp-ind-012",
    cabinetId: "demo-individual-declarant",
    taxType: "pdfo",
    taxTypeLabel: "ПДФО (продаж криптовалюти)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 4140,
    status: "not-created",
    statusLabel: "Не створено",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11010100",
  },
  {
    id: "tp-ind-013",
    cabinetId: "demo-individual-declarant",
    taxType: "military",
    taxTypeLabel: "ВЗ (продаж криптовалюти)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 1150,
    status: "not-created",
    statusLabel: "Не створено",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11011000",
  },
  // 1.22: Другий продаж ТЗ — ПДФО 5% + ВЗ 1.5%
  {
    id: "tp-ind-014",
    cabinetId: "demo-individual-declarant",
    taxType: "pdfo",
    taxTypeLabel: "ПДФО (продаж мотоцикла — 2-й продаж ТЗ)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 4750,
    status: "not-created",
    statusLabel: "Не створено",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11010100",
  },
  {
    id: "tp-ind-015",
    cabinetId: "demo-individual-declarant",
    taxType: "military",
    taxTypeLabel: "ВЗ (продаж мотоцикла — 2-й продаж ТЗ)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 1425,
    status: "not-created",
    statusLabel: "Не створено",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11011000",
  },
  // 3.7: Другий продаж нерухомості — ПДФО 5% + ВЗ 1.5%
  {
    id: "tp-ind-016",
    cabinetId: "demo-individual-declarant",
    taxType: "pdfo",
    taxTypeLabel: "ПДФО (продаж гаражу — 2-й продаж нерухомості)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 9000,
    status: "not-created",
    statusLabel: "Не створено",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11010100",
  },
  {
    id: "tp-ind-017",
    cabinetId: "demo-individual-declarant",
    taxType: "military",
    taxTypeLabel: "ВЗ (продаж гаражу — 2-й продаж нерухомості)",
    period: "2024 рік",
    year: 2024,
    amountToPay: 2700,
    status: "not-created",
    statusLabel: "Не створено",
    deadline: "2025-07-31",
    createdAt: getDateInPast(5),
    budgetCode: "11011000",
  },
];

// ============================================
// CONTRACTOR PAYMENTS (2)
// ============================================

export const individualContractorPayments: ContractorPayment[] = [
  {
    id: "cp-ind-001",
    cabinetId: "demo-individual-declarant",
    date: "2024-02-05",
    contractor: "КНУ ім. Тараса Шевченка",
    contractorId: "c-ind-5",
    contractorCode: "02070987",
    purpose: "Оплата за навчання — магістратура, юрфак, 1 семестр 2024",
    amount: 32000,
    status: "paid",
    statusLabel: "Сплачено",
    paymentPurposeType: "services",
    relatedDocumentId: "doc-ind-d-007",
    bankProvider: "monobank",
    bankLabel: "Monobank",
  },
  {
    id: "cp-ind-002",
    cabinetId: "demo-individual-declarant",
    date: "2024-07-15",
    contractor: "МЦ «Добробут»",
    contractorId: "c-ind-4",
    contractorCode: "38745612",
    purpose: "Оплата за реабілітацію — курс відновлювальної терапії",
    amount: 18500,
    status: "paid",
    statusLabel: "Сплачено",
    paymentPurposeType: "services",
    relatedDocumentId: "doc-ind-d-009",
    bankProvider: "monobank",
    bankLabel: "Monobank",
  },
];

// ============================================
// REPORTS (4)
// ============================================

export const individualReports: Report[] = [
  {
    id: "rep-ind-001",
    type: "pdfo",
    typeLabel: "ПДФО",
    name: "Декларація про майновий стан і доходи за 2024 рік",
    period: "year",
    periodLabel: "2024 рік",
    year: 2024,
    deadline: "2025-05-01",
    status: "review" as ReportStatus,
    statusLabel: "На перевірку",
    draftProgress: 75,
    amountToPay: 67400,
    dataSources: ["manual"],
    cabinetId: "demo-individual-declarant",
    formCode: "F0100114",
    history: [
      { date: getDateInPast(5), action: "AI сформував чернетку декларації", user: "Система" },
      { date: getDateInPast(3), action: "Додано інвестиційні доходи з IBKR", user: "Ткаченко О.В." },
      { date: getDateInPast(2), action: "Розраховано ПДФО з іноземної зарплати (КУПО)", user: "Система" },
    ],
  },
  {
    id: "rep-ind-002",
    type: "pdfo",
    typeLabel: "ПДФО",
    name: "Декларація про майновий стан і доходи за 2023 рік",
    period: "year",
    periodLabel: "2023 рік",
    year: 2023,
    deadline: "2024-05-01",
    status: "accepted" as ReportStatus,
    statusLabel: "Прийнято",
    amountToPay: 48200,
    submittedDate: "2024-04-15",
    acceptedDate: "2024-04-22",
    dataSources: ["manual"],
    cabinetId: "demo-individual-declarant",
    formCode: "F0100114",
    submissionChannel: "tax-cabinet",
  },
  {
    id: "rep-ind-003",
    type: "pdfo",
    typeLabel: "Податкова знижка",
    name: "Декларація для податкової знижки за 2024 рік",
    period: "year",
    periodLabel: "2024 рік",
    year: 2024,
    deadline: "2025-12-31",
    status: "review" as ReportStatus,
    statusLabel: "На перевірку",
    draftProgress: 60,
    amountToPay: -12600,
    dataSources: ["manual"],
    cabinetId: "demo-individual-declarant",
    formCode: "F0100114",
    history: [
      { date: getDateInPast(3), action: "AI розрахував потенційну знижку", user: "Система" },
      { date: getDateInPast(2), action: "Додано квитанції за навчання (66 000 ₴)", user: "Ткаченко О.В." },
      { date: getDateInPast(1), action: "Додано квитанцію за медицину (18 500 ₴)", user: "Ткаченко О.В." },
    ],
  },
  {
    id: "rep-ind-004",
    type: "other",
    typeLabel: "КІК",
    name: "Звіт про контрольовані іноземні компанії (КІК) — 2024",
    period: "year",
    periodLabel: "2024 рік",
    year: 2024,
    deadline: "2025-05-01",
    status: "scheduled" as ReportStatus,
    statusLabel: "Заплановано",
    dataSources: ["manual"],
    cabinetId: "demo-individual-declarant",
    history: [
      { date: getDateInPast(10), action: "Перевірка необхідності подання звіту КІК", user: "Система" },
    ],
  },
  // TC-AMENDMENT: Уточнююча декларація за 2023 рік
  {
    id: "rep-ind-005",
    type: "pdfo",
    typeLabel: "ПДФО (уточнююча)",
    name: "Уточнююча декларація про майновий стан і доходи за 2023 рік",
    period: "year",
    periodLabel: "2023 рік",
    year: 2023,
    deadline: "2025-05-01",
    status: "review" as ReportStatus,
    statusLabel: "На перевірку",
    draftProgress: 90,
    amountToPay: 55800,
    dataSources: ["manual"],
    cabinetId: "demo-individual-declarant",
    formCode: "F0100114",
    
    // Correction metadata
    isCorrection: true,
    correctionOf: "rep-ind-002",
    correctionNumber: 1,
    correctionReason: "Виявлено незадекларований дохід від оренди квартири та дивіденди IBKR за 2023 рік",
    
    // Amendment diff
    amendmentDiff: [
      { field: "totalIncome", label: "Загальний дохід", oldValue: 385000, newValue: 421500, changeType: "changed" },
      { field: "rentalIncome", label: "Дохід від оренди", oldValue: null, newValue: 24000, changeType: "added" },
      { field: "foreignDividends", label: "Дивіденди (іноземні)", oldValue: 0, newValue: 12500, changeType: "added" },
      { field: "pdfoToPay", label: "ПДФО до сплати", oldValue: 48200, newValue: 55800, changeType: "changed" },
      { field: "vzToPay", label: "ВЗ до сплати", oldValue: 5775, newValue: 6323, changeType: "changed" },
      { field: "selfDisclosurePenalty", label: "Штраф (3% самовиявлення)", oldValue: null, newValue: 228, changeType: "added" },
    ],
    
    history: [
      { date: getDateInPast(7), action: "Виявлено розбіжність: незадекларований дохід від оренди за 2023 рік", user: "Система" },
      { date: getDateInPast(5), action: "AI виявив відсутні дивіденди IBKR за 2023 у первинній декларації", user: "Система" },
      { date: getDateInPast(3), action: "Сформовано уточнюючу декларацію з перерахунком ПДФО та ВЗ", user: "Система" },
      { date: getDateInPast(2), action: "Розраховано штраф 3% самовиявлення (228 ₴)", user: "Система" },
      { date: getDateInPast(1), action: "Декларація готова до перевірки користувачем", user: "Система" },
    ],
  },

  // ============================================
  // ДЕМО-ЧЕРНЕТКИ для нового флоу "Створити звіт → перевірити → подати"
  // ============================================

  // 6. Декларація 2025 (scheduled) — головний демо-кейс для створення чернетки
  {
    id: "rep-ind-006",
    type: "pdfo",
    typeLabel: "ПДФО",
    name: "Декларація про майновий стан і доходи за 2025 рік",
    period: "year",
    periodLabel: "2025 рік",
    year: 2025,
    deadline: "2026-05-01",
    status: "scheduled" as ReportStatus,
    statusLabel: "Заплановано",
    draftProgress: 0,
    amountToPay: 32710,
    dataSources: ["manual", "integrations"],
    cabinetId: "demo-individual-declarant",
    formCode: "J1700604",
    submissionChannel: "tax-cabinet",
    legalBasis: {
      article: "ст. 179 ПКУ",
      description: "Подання декларації про майновий стан і доходи фізичної особи",
      deadline: "До 1 травня року, наступного за звітним",
      effectiveFrom: "2011-01-01",
    },
    history: [
      { date: getDateInPast(15), action: "Заплановано формування декларації за 2025 рік", user: "Система" },
      { date: getDateInPast(7), action: "Зібрано дані з джерел: IBKR, оренда, іноземні дивіденди", user: "Система" },
    ],
  },

  // 7. ВЗ за грудень 2025 — ставка 5%, інвестдоходи
  {
    id: "rep-ind-007",
    type: "vz",
    typeLabel: "Військовий збір",
    name: "Військовий збір з інвестиційних доходів за грудень 2025",
    period: "month",
    periodLabel: "Грудень 2025",
    year: 2025,
    month: 12,
    deadline: "2026-01-30",
    status: "scheduled" as ReportStatus,
    statusLabel: "Заплановано",
    draftProgress: 0,
    amountToPay: 425,
    dataSources: ["integrations"],
    cabinetId: "demo-individual-declarant",
    formCode: "J1700604",
    submissionChannel: "tax-cabinet",
    legalBasis: {
      article: "п. 161 підрозд. 10 ПКУ",
      description: "Військовий збір з доходів фізичних осіб",
      rate: "5%",
      effectiveFrom: "2025-01-01",
    },
    calculation: {
      type: "vz",
      data: {
        baseAmount: 8500,
        rate: 0.05,
        calculatedVZ: 425,
        toPay: 425,
        isLinkedToEP: false,
      },
    },
    history: [
      { date: getDateInPast(10), action: "Зафіксовано інвестдохід від продажу акцій NVDA — 8 500 ₴", user: "Система" },
      { date: getDateInPast(8), action: "Розраховано ВЗ за ставкою 5% (з 01.01.2025)", user: "Система" },
    ],
  },

  // 8. Податкова знижка за 2024 рік (scheduled) — повернення з бюджету
  {
    id: "rep-ind-008",
    type: "pdfo",
    typeLabel: "Податкова знижка",
    name: "Заява на податкову знижку за 2024 рік (навчання + іпотека)",
    period: "year",
    periodLabel: "2024 рік",
    year: 2024,
    deadline: "2025-12-31",
    status: "scheduled" as ReportStatus,
    statusLabel: "Заплановано",
    draftProgress: 0,
    amountToPay: -8640,
    dataSources: ["manual"],
    cabinetId: "demo-individual-declarant",
    formCode: "J1302101",
    submissionChannel: "tax-cabinet",
    legalBasis: {
      article: "ст. 166 ПКУ",
      description: "Право на податкову знижку (навчання — пп. 166.3.3, іпотека — пп. 166.3.1)",
      deadline: "До 31 грудня року, наступного за звітним",
      effectiveFrom: "2011-01-01",
    },
    history: [
      { date: getDateInPast(20), action: "AI виявив право на податкову знижку: 30 000 ₴ навчання + 18 000 ₴ іпотека", user: "Система" },
      { date: getDateInPast(15), action: "Розраховано суму до повернення: 8 640 ₴ (18% від 48 000 ₴)", user: "Система" },
    ],
  },

  // 9. Декларація 2024 (submitted) — для порівняння UI вже поданого звіту
  {
    id: "rep-ind-009",
    type: "pdfo",
    typeLabel: "ПДФО",
    name: "Декларація про майновий стан і доходи за 2024 рік (подана)",
    period: "year",
    periodLabel: "2024 рік",
    year: 2024,
    deadline: "2025-05-01",
    status: "submitted" as ReportStatus,
    statusLabel: "Подано",
    amountToPay: 67400,
    submittedDate: "2025-04-22",
    dataSources: ["manual", "integrations"],
    cabinetId: "demo-individual-declarant",
    formCode: "J1700604",
    submissionChannel: "tax-cabinet",
    legalBasis: {
      article: "ст. 179 ПКУ",
      description: "Подання декларації про майновий стан і доходи фізичної особи",
      effectiveFrom: "2011-01-01",
    },
    history: [
      { date: "2025-04-15", action: "Чернетку сформовано", user: "Система" },
      { date: "2025-04-20", action: "Перевірено користувачем", user: "Ткаченко О.В." },
      { date: "2025-04-22", action: "Подано через Кабінет ДПС", user: "Ткаченко О.В." },
    ],
  },

  // 10. ВЗ листопад 2024 (accepted) — стара ставка 1.5% для демо переходу
  {
    id: "rep-ind-010",
    type: "vz",
    typeLabel: "Військовий збір",
    name: "Військовий збір з доходів за листопад 2024",
    period: "month",
    periodLabel: "Листопад 2024",
    year: 2024,
    month: 11,
    deadline: "2024-12-30",
    status: "accepted" as ReportStatus,
    statusLabel: "Прийнято",
    amountToPay: 113,
    submittedDate: "2024-12-15",
    acceptedDate: "2024-12-18",
    dataSources: ["integrations"],
    cabinetId: "demo-individual-declarant",
    formCode: "J1700604",
    submissionChannel: "tax-cabinet",
    legalBasis: {
      article: "п. 161 підрозд. 10 ПКУ",
      description: "Військовий збір (історична ставка до 31.12.2024)",
      rate: "1,5%",
      effectiveFrom: "2014-08-03",
    },
    calculation: {
      type: "vz",
      data: {
        baseAmount: 7500,
        rate: 0.015,
        calculatedVZ: 113,
        toPay: 113,
        isLinkedToEP: false,
      },
    },
    history: [
      { date: "2024-12-10", action: "Зафіксовано інвестдохід — 7 500 ₴", user: "Система" },
      { date: "2024-12-12", action: "Розраховано ВЗ за історичною ставкою 1,5%", user: "Система" },
      { date: "2024-12-15", action: "Подано через Кабінет ДПС", user: "Ткаченко О.В." },
      { date: "2024-12-18", action: "Прийнято ДПС", user: "ДПС України" },
    ],
  },
];
