/**
 * Демо-дані інвестиційних позицій
 * Покриває: US/EU акції, ETF, облігації, ОВДП, крипто, ESOP, DeFi, P2P
 */
import type { InvestmentPosition } from "./investmentTypes";

// ---- CLOSED POSITIONS (realized P&L) ----
export const investmentPositions: InvestmentPosition[] = [
  // --- Original positions ---
  {
    id: "inv-pos-1",
    asset: "Apple Inc.",
    ticker: "AAPL",
    type: "stock",
    operationType: "sell",
    buyDate: "15.03.2024",
    buyQty: 10,
    buyPriceUsd: 150,
    buyCommission: 1.5,
    nbuRateBuy: 38.45,
    sellDate: "15.08.2025",
    sellPriceUsd: 270,
    sellCommission: 2.0,
    nbuRateSell: 41.22,
    status: "declared",
    sector: "Technology",
    country: "US",
  },
  {
    id: "inv-pos-2",
    asset: "NVIDIA Corp.",
    ticker: "NVDA",
    type: "stock",
    operationType: "sell",
    buyDate: "10.01.2024",
    buyQty: 5,
    buyPriceUsd: 480,
    buyCommission: 2.0,
    nbuRateBuy: 37.98,
    sellDate: "20.11.2025",
    sellPriceUsd: 1040,
    sellCommission: 3.5,
    nbuRateSell: 41.55,
    status: "declared",
    sector: "Technology",
    country: "US",
    corporateAction: {
      type: "split",
      date: "10.06.2024",
      ratio: 10,
      description: "NVDA 10:1 stock split. Cost basis adjusted: $4800→$480/share equivalent.",
    },
  },
  {
    id: "inv-pos-3",
    asset: "Microsoft Corp.",
    ticker: "MSFT",
    type: "dividend",
    operationType: "dividend",
    buyDate: "01.02.2023",
    buyQty: 20,
    buyPriceUsd: 250,
    buyCommission: 2.0,
    nbuRateBuy: 36.80,
    grossDividendUsd: 400,
    withholdingRate: 0.15,
    dividendDate: "15.06.2025",
    nbuRateDividend: 40.85,
    status: "declared",
    sector: "Technology",
    country: "US",
  },
  {
    id: "inv-pos-4",
    asset: "Tesla Inc.",
    ticker: "TSLA",
    type: "stock",
    operationType: "hold",
    buyDate: "05.04.2024",
    buyQty: 3,
    buyPriceUsd: 165,
    buyCommission: 1.0,
    nbuRateBuy: 39.10,
    status: "in-portfolio",
    sector: "Automotive",
    country: "US",
  },
  {
    id: "inv-pos-5",
    asset: "iShares Core S&P 500",
    ticker: "IVV",
    type: "etf",
    operationType: "hold",
    buyDate: "20.05.2024",
    buyQty: 2,
    buyPriceUsd: 530,
    buyCommission: 1.5,
    nbuRateBuy: 39.85,
    status: "in-portfolio",
    sector: "Index",
    country: "US",
  },
  {
    id: "inv-pos-6",
    asset: "Bitcoin",
    ticker: "BTC",
    type: "crypto",
    operationType: "sell",
    buyDate: "01.06.2024",
    buyQty: 1,
    buyPriceUsd: 1770,
    buyCommission: 5.0,
    nbuRateBuy: 40.50,
    sellDate: "05.12.2025",
    sellPriceUsd: 2428,
    sellCommission: 7.0,
    nbuRateSell: 41.60,
    status: "declared",
    sector: "Crypto",
    country: "Global",
  },

  // --- Priority 2: New asset classes ---

  // EU Stock — Siemens (Germany, WHT 26.375% → cap at 18%)
  {
    id: "inv-pos-7",
    asset: "Siemens AG",
    ticker: "SIE",
    type: "dividend",
    operationType: "dividend",
    currency: "EUR",
    buyDate: "10.02.2024",
    buyQty: 5,
    buyPriceUsd: 165, // EUR converted
    buyCommission: 3.0,
    nbuRateBuy: 42.10,
    grossDividendUsd: 220, // EUR equivalent in USD
    withholdingRate: 0.26375, // Germany
    dividendDate: "20.09.2025",
    nbuRateDividend: 44.60,
    status: "declared",
    sector: "Industrial",
    country: "DE",
  },

  // ETF accumulating — VWCE (Ireland domicile, no dividends)
  {
    id: "inv-pos-8",
    asset: "Vanguard FTSE All-World (Acc)",
    ticker: "VWCE",
    type: "etf",
    operationType: "hold",
    currency: "EUR",
    buyDate: "01.04.2024",
    buyQty: 3,
    buyPriceUsd: 115,
    buyCommission: 1.2,
    nbuRateBuy: 39.30,
    status: "in-portfolio",
    sector: "Index",
    country: "IE",
  },

  // ETF distributing — VYM (US, WHT 15%)
  {
    id: "inv-pos-9",
    asset: "Vanguard High Dividend Yield",
    ticker: "VYM",
    type: "dividend",
    operationType: "dividend",
    buyDate: "15.03.2024",
    buyQty: 10,
    buyPriceUsd: 120,
    buyCommission: 1.0,
    nbuRateBuy: 38.45,
    grossDividendUsd: 180,
    withholdingRate: 0.15,
    dividendDate: "15.09.2025",
    nbuRateDividend: 41.30,
    status: "declared",
    sector: "Index",
    country: "US",
  },

  // ОВДП (UA government bond — UAH denominated)
  {
    id: "inv-pos-10",
    asset: "ОВДП UA4000227072",
    ticker: "ОВДП-2024",
    type: "ovdp",
    operationType: "coupon",
    currency: "UAH",
    buyDate: "15.01.2024",
    buyQty: 1,
    buyPriceUsd: 100000, // nominal UAH (stored as "price")
    buyCommission: 0,
    nbuRateBuy: 1, // UAH → rate = 1
    nominal: 100000,
    couponRate: 0.19, // 19% annual
    couponDate: "15.07.2025",
    nbuRateDividend: 1,
    status: "declared",
    sector: "Government",
    country: "UA",
  },

  // Corporate bond (USD)
  {
    id: "inv-pos-11",
    asset: "Corp Bond XYZ 2026",
    ticker: "XYZ-BOND",
    type: "bond",
    operationType: "sell",
    buyDate: "01.03.2024",
    buyQty: 10,
    buyPriceUsd: 980, // bought at 98% of face
    buyCommission: 5.0,
    nbuRateBuy: 38.20,
    sellDate: "01.11.2025",
    sellPriceUsd: 1020, // sold at 102%
    sellCommission: 5.0,
    nbuRateSell: 41.40,
    nominal: 10000, // 10 bonds × $1000 face
    couponRate: 0.055,
    couponDate: "01.09.2025",
    nbuRateDividend: 41.10,
    status: "declared",
    sector: "Corporate Bond",
    country: "US",
  },

  // --- Priority 3: ESOP, DeFi, P2P ---

  // ESOP/RSU
  {
    id: "inv-pos-12",
    asset: "TechCorp Inc. (ESOP)",
    ticker: "TCORP",
    type: "esop",
    operationType: "exercise",
    buyDate: "01.01.2022",
    buyQty: 100,
    buyPriceUsd: 0,
    buyCommission: 0,
    nbuRateBuy: 27.50,
    grantDate: "01.01.2022",
    strikePrice: 50,
    fmvAtExercise: 120,
    exerciseDate: "15.07.2025",
    nbuRateSell: 40.90,
    status: "declared",
    sector: "Technology",
    country: "US",
  },

  // DeFi yield (ETH staking)
  {
    id: "inv-pos-13",
    asset: "Ethereum Staking (Lido)",
    ticker: "stETH",
    type: "defi",
    operationType: "yield",
    buyDate: "01.01.2024",
    buyQty: 2,
    buyPriceUsd: 4800,
    buyCommission: 0,
    nbuRateBuy: 37.50,
    yieldAmount: 380,
    yieldSource: "Lido staking rewards",
    nbuRateDividend: 41.20,
    dividendDate: "31.12.2025",
    status: "declared",
    sector: "DeFi",
    country: "Global",
  },

  // P2P lending — income
  {
    id: "inv-pos-14",
    asset: "Mintos P2P Portfolio",
    ticker: "MINTOS",
    type: "p2p",
    operationType: "yield",
    currency: "EUR",
    buyDate: "01.06.2024",
    buyQty: 1,
    buyPriceUsd: 2000,
    buyCommission: 0,
    nbuRateBuy: 40.50,
    yieldAmount: 150,
    yieldSource: "P2P interest income",
    nbuRateDividend: 44.20,
    dividendDate: "31.12.2025",
    status: "declared",
    sector: "P2P Lending",
    country: "LV",
  },

  // P2P lending — default (loss)
  {
    id: "inv-pos-15",
    asset: "Bondora Go&Grow (Default)",
    ticker: "BONDORA",
    type: "p2p",
    operationType: "yield",
    currency: "EUR",
    buyDate: "15.03.2024",
    buyQty: 1,
    buyPriceUsd: 500,
    buyCommission: 0,
    nbuRateBuy: 38.45,
    yieldAmount: -80,
    yieldSource: "P2P default loss",
    nbuRateDividend: 44.20,
    dividendDate: "30.11.2025",
    status: "declared",
    sector: "P2P Lending",
    country: "EE",
  },

  // --- Priority 4: Corporate actions demo ---

  // Merger: Twitter → X Corp
  {
    id: "inv-pos-16",
    asset: "X Corp (ex-Twitter)",
    ticker: "X",
    type: "stock",
    operationType: "sell",
    buyDate: "10.01.2024",
    buyQty: 50,
    buyPriceUsd: 54,
    buyCommission: 3.0,
    nbuRateBuy: 37.80,
    sellDate: "01.10.2025",
    sellPriceUsd: 42,
    sellCommission: 3.0,
    nbuRateSell: 41.30,
    status: "declared",
    sector: "Technology",
    country: "US",
    corporateAction: {
      type: "merger",
      date: "28.10.2022",
      newTicker: "X",
      description: "Twitter Inc. → X Corp. Elon Musk acquisition. Ticker change TWTR → X. Cost basis unchanged.",
    },
  },

  // Spinoff: Johnson & Johnson → Kenvue
  {
    id: "inv-pos-17",
    asset: "Kenvue Inc. (spinoff JNJ)",
    ticker: "KVUE",
    type: "stock",
    operationType: "hold",
    buyDate: "04.05.2023",
    buyQty: 10,
    buyPriceUsd: 26.5,
    buyCommission: 0,
    nbuRateBuy: 36.90,
    status: "in-portfolio",
    sector: "Healthcare",
    country: "US",
    corporateAction: {
      type: "spinoff",
      date: "04.05.2023",
      description: "JNJ spinoff → KVUE. Cost basis allocated: 15% of original JNJ cost basis ($176.65) = $26.50/share.",
    },
  },

  // --- Priority: New asset classes (A.12, A.13, A.15) ---

  // REIT — Realty Income (US, WHT 15%, with return of capital)
  {
    id: "inv-pos-18",
    asset: "Realty Income Corp.",
    ticker: "O",
    type: "reit",
    operationType: "dividend",
    buyDate: "15.02.2024",
    buyQty: 20,
    buyPriceUsd: 55,
    buyCommission: 1.5,
    nbuRateBuy: 37.90,
    grossDividendUsd: 120,
    withholdingRate: 0.15,
    dividendDate: "15.10.2025",
    nbuRateDividend: 41.40,
    returnOfCapital: 30,
    status: "declared",
    sector: "Real Estate",
    country: "US",
  },

  // Mutual Fund / ПІФ — sell with P&L
  {
    id: "inv-pos-19",
    asset: "ПІФ «Укрсиб Збалансований»",
    ticker: "ПІФ-УКР",
    type: "fund",
    operationType: "sell",
    currency: "UAH",
    buyDate: "01.03.2024",
    buyQty: 100,
    buyPriceUsd: 120,
    buyCommission: 0,
    nbuRateBuy: 1,
    sellDate: "01.11.2025",
    sellPriceUsd: 135,
    sellCommission: 0,
    nbuRateSell: 1,
    status: "declared",
    sector: "Mutual Fund",
    country: "UA",
  },

  // Precious Metal — Gold (XAU), sell with P&L
  {
    id: "inv-pos-20",
    asset: "Gold (XAU)",
    ticker: "XAU",
    type: "metal",
    operationType: "sell",
    buyDate: "10.01.2024",
    buyQty: 1,
    buyPriceUsd: 2050,
    buyCommission: 15,
    nbuRateBuy: 37.80,
    sellDate: "15.10.2025",
    sellPriceUsd: 2680,
    sellCommission: 15,
    nbuRateSell: 41.40,
    status: "declared",
    sector: "Commodities",
    country: "Global",
  },
];

// ---- MULTI-LOT BUY LOTS (Amazon FIFO example) ----

export const multiLotBuyLots: InvestmentPosition[] = [
  {
    id: "inv-lot-amzn-1",
    asset: "Amazon.com Inc.",
    ticker: "AMZN",
    type: "stock",
    operationType: "hold",
    buyDate: "01.03.2024",
    buyQty: 10,
    buyPriceUsd: 130,
    buyCommission: 1.5,
    nbuRateBuy: 38.20,
    status: "declared",
    sector: "Technology",
    country: "US",
  },
  {
    id: "inv-lot-amzn-2",
    asset: "Amazon.com Inc.",
    ticker: "AMZN",
    type: "stock",
    operationType: "hold",
    buyDate: "15.05.2024",
    buyQty: 15,
    buyPriceUsd: 145,
    buyCommission: 1.5,
    nbuRateBuy: 39.50,
    status: "declared",
    sector: "Technology",
    country: "US",
  },
  {
    id: "inv-lot-amzn-3",
    asset: "Amazon.com Inc.",
    ticker: "AMZN",
    type: "stock",
    operationType: "hold",
    buyDate: "01.08.2024",
    buyQty: 10,
    buyPriceUsd: 160,
    buyCommission: 2.0,
    nbuRateBuy: 40.80,
    status: "declared",
    sector: "Technology",
    country: "US",
  },
];

export const multiLotSellPosition: InvestmentPosition = {
  id: "inv-sell-amzn",
  asset: "Amazon.com Inc.",
  ticker: "AMZN",
  type: "stock",
  operationType: "sell",
  buyDate: "01.03.2024",
  buyQty: 25,
  buyPriceUsd: 0,
  buyCommission: 0,
  nbuRateBuy: 38.20,
  sellDate: "10.12.2025",
  sellPriceUsd: 185,
  sellCommission: 3.5,
  nbuRateSell: 41.70,
  relatedLotIds: ["inv-lot-amzn-1", "inv-lot-amzn-2", "inv-lot-amzn-3"],
  status: "declared",
  sector: "Technology",
  country: "US",
};
